# Generated by Django 2.1.5 on 2019-05-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='active',
            field=models.BooleanField(blank=True, default='1', null=True),
        ),
    ]
