# Generated by Django 2.1.5 on 2019-03-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(choices=[('Alameda', 'Alameda'), ('Alpine', 'Alpine'), ('Amador', 'Amador'), ('Butte', 'Butte'), ('Colusa', 'Colusa'), ('Calaveras', 'Calaveras'), ('Contra Costa', 'Contra Costa'), ('Del Norte', 'Del Norte'), ('El Dorado', 'El Dorado'), ('Fresno', 'Fresno'), ('Glenn', 'Glenn'), ('Humboldt', 'Humboldt'), ('Imperial', 'Imperial'), ('Inyo', 'Inyo'), ('Kern', 'Kern'), ('Kings', 'Kings'), ('Klamath', 'Klamath'), ('Lake', 'Lake'), ('Lassen', 'Lassen'), ('Los Angeles', 'Los Angeles'), ('Madera', 'Madera'), ('Marin', 'Marin'), ('Mariposa', 'Mariposa'), ('Mendocino', 'Mendocino'), ('Merced', 'Merced'), ('Modoc', 'Modoc'), ('Mono', 'Mono'), ('Monterey', 'Monterey'), ('Napa', 'Napa'), ('Nevada', 'Nevada'), ('Orange', 'Orange'), ('Placer', 'Placer'), ('Plumas', 'Plumas'), ('Riverside', 'Riverside'), ('Sacramento', 'Sacramento'), ('San Benito', 'San Benito'), ('San Bernardino', 'San Bernardino'), ('San Diego', 'San Diego'), ('San Francisco', 'San Francisco'), ('San Joaquin', 'San Joaquin'), ('San Luis Obispo', 'San Luis Obispo'), ('San Mateo', 'San Mateo'), ('Santa Barbara', 'Santa Barbara'), ('Santa Clara', 'Santa Clara'), ('Santa Cruz', 'Santa Cruz'), ('Shasta', 'Shasta'), ('Sierra', 'Sierra'), ('Siskiyou', 'Siskiyou'), ('Solano', 'Solano'), ('Sonoma', 'Sonoma'), ('Stanislaus', 'Stanislaus'), ('Sutter', 'Sutter'), ('Tehama', 'Tehama'), ('Trinity', 'Trinity'), ('Tulare', 'Tulare'), ('Tuolumne', 'Tuolumne'), ('Ventura', 'Ventura'), ('Yolo', 'Yolo'), ('Yuba', 'Yuba'), ('Other/None', 'Other/None')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intake',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='intake',
            name='preferred_medium',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Print', 'Print'), ('Large Print', 'Large Print'), ('Braille', 'Braille'), ('E-Mail', 'E-Mail'), ('Cassette', 'Cassette')], max_length=150),
        ),
    ]
