# Generated by Django 2.1.5 on 2019-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0002_auto_20190527_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='asthma',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='cancer',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='crime',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='diabetes',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='dialysis',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='hearing_loss',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='heart',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='high_bp',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='learning_disability',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='memory_loss',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='mobility',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='neuropathy',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='pain',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='parole',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='seizure',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='stroke',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='substance_abuse',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='veteran',
            field=models.BooleanField(blank=True, default='0'),
        ),
    ]
