# Generated by Django 2.1.7 on 2019-04-20 17:51

from django.db import migrations, models
import django.db.models.deletion
import lynx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0002_auto_20190317_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('address_one', models.CharField(blank=True, max_length=150)),
                ('address_two', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=75)),
                ('state', models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], default='California', max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('phone_day', models.CharField(blank=True, max_length=150)),
                ('phone_other', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact')),
                ('user_id', models.ForeignKey(on_delete=models.SET(lynx.models.get_sentinel_user), to='lynx.User')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='address_one',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='bad_address',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(blank=True, choices=[('Alameda', 'Alameda'), ('Alpine', 'Alpine'), ('Amador', 'Amador'), ('Butte', 'Butte'), ('Colusa', 'Colusa'), ('Calaveras', 'Calaveras'), ('Contra Costa', 'Contra Costa'), ('Del Norte', 'Del Norte'), ('El Dorado', 'El Dorado'), ('Fresno', 'Fresno'), ('Glenn', 'Glenn'), ('Humboldt', 'Humboldt'), ('Imperial', 'Imperial'), ('Inyo', 'Inyo'), ('Kern', 'Kern'), ('Kings', 'Kings'), ('Klamath', 'Klamath'), ('Lake', 'Lake'), ('Lassen', 'Lassen'), ('Los Angeles', 'Los Angeles'), ('Madera', 'Madera'), ('Marin', 'Marin'), ('Mariposa', 'Mariposa'), ('Mendocino', 'Mendocino'), ('Merced', 'Merced'), ('Modoc', 'Modoc'), ('Mono', 'Mono'), ('Monterey', 'Monterey'), ('Napa', 'Napa'), ('Nevada', 'Nevada'), ('Orange', 'Orange'), ('Placer', 'Placer'), ('Plumas', 'Plumas'), ('Riverside', 'Riverside'), ('Sacramento', 'Sacramento'), ('San Benito', 'San Benito'), ('San Bernardino', 'San Bernardino'), ('San Diego', 'San Diego'), ('San Francisco', 'San Francisco'), ('San Joaquin', 'San Joaquin'), ('San Luis Obispo', 'San Luis Obispo'), ('San Mateo', 'San Mateo'), ('Santa Barbara', 'Santa Barbara'), ('Santa Clara', 'Santa Clara'), ('Santa Cruz', 'Santa Cruz'), ('Shasta', 'Shasta'), ('Sierra', 'Sierra'), ('Siskiyou', 'Siskiyou'), ('Solano', 'Solano'), ('Sonoma', 'Sonoma'), ('Stanislaus', 'Stanislaus'), ('Sutter', 'Sutter'), ('Tehama', 'Tehama'), ('Trinity', 'Trinity'), ('Tulare', 'Tulare'), ('Tuolumne', 'Tuolumne'), ('Ventura', 'Ventura'), ('Yolo', 'Yolo'), ('Yuba', 'Yuba'), ('Other/None', 'Other/None')], max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], default='California', max_length=25),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='intake',
            name='crime_info',
            field=models.TextField(blank=True),
        ),
    ]
