# Generated by Django 2.1.5 on 2019-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0003_auto_20190527_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='diabetes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='intake',
            name='veteran',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
