# Generated by Django 2.1.5 on 2019-05-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0005_auto_20190527_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='bad_address',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='deceased',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='do_not_contact',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='remove_mailing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
