# Generated by Django 2.1.5 on 2019-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0007_auto_20190616_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='outsideagency',
            options={'verbose_name_plural': 'Outside Agencies'},
        ),
        migrations.AddField(
            model_name='contact',
            name='donor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='hired',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
