# Generated by Django 2.1.5 on 2019-07-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0011_auto_20190721_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnote',
            name='attendance',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='billed_units',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='instructional_units',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='obstacles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='recommendations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='students_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='successes',
            field=models.TextField(null=True),
        ),
    ]
