# Generated by Django 2.1.5 on 2019-07-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0012_auto_20190721_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='obstacles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='successes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
