# Generated by Django 2.1.5 on 2019-08-30 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0013_auto_20190723_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='type',
            new_name='email_type',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='address_one',
            new_name='emergency_address_one',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='address_two',
            new_name='emergency_address_two',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='city',
            new_name='emergency_city',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='country',
            new_name='emergency_country',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='notes',
            new_name='emergency_notes',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='state',
            new_name='emergency_state',
        ),
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='zip_code',
            new_name='emergency_zip_code',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='type',
            new_name='phone_type',
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
