# Generated by Django 2.1.5 on 2019-09-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0014_auto_20190829_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='eye_condition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
