# Generated by Django 2.1.5 on 2019-09-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0015_auto_20190907_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
