# Generated by Django 2.1.5 on 2019-09-21 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lynx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0016_contact_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('vision_screening', models.BooleanField(blank=True, default=False)),
                ('treatment', models.BooleanField(blank=True, default=False)),
                ('at_devices', models.BooleanField(blank=True, default=False)),
                ('at_services', models.BooleanField(blank=True, default=False)),
                ('independent_living', models.BooleanField(blank=True, default=False)),
                ('orientation', models.BooleanField(blank=True, default=False)),
                ('communications', models.BooleanField(blank=True, default=False)),
                ('dls', models.BooleanField(blank=True, default=False)),
                ('support', models.BooleanField(blank=True, default=False)),
                ('advocacy', models.BooleanField(blank=True, default=False)),
                ('counseling', models.BooleanField(blank=True, default=False)),
                ('information', models.BooleanField(blank=True, default=False)),
                ('services', models.BooleanField(blank=True, default=False)),
                ('retreat', models.BooleanField(blank=True, default=False)),
                ('in_home', models.BooleanField(blank=True, default=False)),
                ('seminar', models.BooleanField(blank=True, default=False)),
                ('modesto', models.BooleanField(blank=True, default=False)),
                ('group', models.BooleanField(blank=True, default=False)),
                ('community', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(lynx.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
