# Generated by Django 2.1.5 on 2019-09-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0017_sipnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='core_client',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='sip_client',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='sipnote',
            name='note_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
