# Generated by Django 2.1.5 on 2019-09-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0018_auto_20190921_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='class_size',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=25, null=True),
        ),
    ]
