# Generated by Django 2.1.5 on 2019-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0021_auto_20191006_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='access_news',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='careers_plus',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='careers_plus_youth',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='other_services',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='volunteer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
