# Generated by Django 2.1.5 on 2019-10-06 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0022_auto_20191006_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
