# Generated by Django 2.1.5 on 2019-10-07 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0023_auto_20191006_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
