# Generated by Django 2.1.5 on 2019-11-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0025_auto_20191020_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], max_length=25),
        ),
    ]
