# Generated by Django 2.1.5 on 2020-03-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0026_contact_salutation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='confidentiality',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='dmv',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='training',
        ),
        migrations.AddField(
            model_name='intake',
            name='geriatric',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='secondary_eye_condition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='age_group',
            field=models.CharField(blank=True, choices=[('50-54', '50-54'), ('55-59', '55-59'), ('60-64', '60-64'), ('65-69', '65-69'), ('70-74', '70-74'), ('75-79', '75-79'), ('80-84', '80-84'), ('85-89', '85-89'), ('90-94', '90-94'), ('95-99', '95-99'), ('100+', '100+')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='education',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Less than High School', 'Less than High School'), ('GED', 'GED'), ('High School', 'High School'), ('Associates', 'Associates'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('White', 'White'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='eye_condition',
            field=models.CharField(blank=True, choices=[('Cataracts', 'Cataracts'), ('Diabetic Retinopathy', 'Diabetic Retinopathy'), ('Glaucoma', 'Glaucoma'), ('Macular Degeneration', 'Macular Degeneration'), ('Other', 'Other')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='performs_tasks',
            field=models.CharField(blank=True, choices=[('Visually', 'Visually'), ('Non-Visually', 'Non-Visually')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='attendance',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Other', 'Other')], default='Present', max_length=150, null=True),
        ),
    ]
