# Generated by Django 2.1.5 on 2020-03-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0027_auto_20200314_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressreport',
            old_name='estimated_hours',
            new_name='long_term_goals_time',
        ),
        migrations.RenameField(
            model_name='progressreport',
            old_name='remaining_objectives',
            new_name='short_term_goals',
        ),
        migrations.AddField(
            model_name='progressreport',
            name='long_term_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='short_term_goals_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
