# Generated by Django 2.1.5 on 2020-03-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0028_auto_20200314_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='authorization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lynx.Authorization'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='long_term_goals_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='short_term_goals_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
