# Generated by Django 2.1.5 on 2020-03-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0029_auto_20200322_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='year',
        ),
    ]
