# Generated by Django 2.1.5 on 2020-04-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0030_remove_progressreport_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='emergency_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intake',
            name='alzheimers_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='arthritis_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='asthma_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='cancer_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='dexterity',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='dexterity_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='diabetes_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='dialysis_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='employer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='geriatric_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='hearing_loss_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='heart_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='high_bp_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='learning_disability_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='memory_loss_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='migraine',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='migraine_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='mobility_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='musculoskeletal_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='neuropathy_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='pain_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='payment_source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='referred_by',
            field=models.CharField(blank=True, choices=[('DOR', 'DOR'), ('Alta', 'Alta'), ('VA', 'VA'), ('Physician', 'Physician'), ('Family/friend', 'Family/friend'), ('Other', 'Other')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='seizure_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='stroke_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='substance_abuse_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Less than 54', 'Less than 54'), ('50-54', '50-54'), ('55-59', '55-59'), ('60-64', '60-64'), ('65-69', '65-69'), ('70-74', '70-74'), ('75-79', '75-79'), ('80-84', '80-84'), ('85-89', '85-89'), ('90-94', '90-94'), ('95-99', '95-99'), ('100+', '100+')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='crime',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='degree',
            field=models.CharField(blank=True, choices=[('Totally Blind (NP or NLP)', 'Totally Blind (NP or NLP)'), ('Legally Blind', 'Legally Blind'), ('Severe Visual Impairment', 'Severe Visual Impairment'), ('Light Perception Only', 'Light Perception Only'), ('Low Vision', 'Low Vision')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='eye_condition',
            field=models.CharField(blank=True, choices=[('Cataracts', 'Cataracts'), ('Cone Rod Dystrophy', 'Cone Rod Dystrophy'), ('Diabetic Retinopathy', 'Diabetic Retinopathy'), ('Glaucoma', 'Glaucoma'), ('Keratoconus', 'Keratoconus'), ('Leber Hereditary Optic Neuropathy (LHON)', 'Leber Hereditary Optic Neuropathy (LHON)'), ('Macular Degeneration', 'Macular Degeneration'), ('Ocular Albinism', 'Ocular Albinism'), ('Optic Nerve Hypoplasia', 'Optic Nerve Hypoplasia'), ('Retinitis Pigmentosa (RP)', 'Retinitis Pigmentosa (RP)'), ('Retinopathy of Prematurity(ROP)', 'Retinopathy of Prematurity(ROP)'), ('Stargardt Disease', 'Stargardt Disease'), ('Stroke-related', 'Stroke-related'), ('Trauma or injury', 'Trauma or injury'), ('Uveitis', 'Uveitis'), ('Other', 'Other')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='hired',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='living_arrangement',
            field=models.CharField(blank=True, choices=[('Live Alone', 'Live Alone'), ('Live With Spouse or Family', 'Live With Spouse or Family'), ('Live With Other', 'Live With Other'), ('Homeless', 'Homeless')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='performs_tasks',
            field=models.CharField(blank=True, choices=[('Visually', 'Visually'), ('Non-Visually', 'Non-Visually'), ('Both', 'Both')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='veteran',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Home', 'Home'), ('Cell', 'Cell'), ('Evening', 'Evening'), ('Day', 'Day'), ('Fax', 'Fax'), ('Other', 'Other')], max_length=25, null=True),
        ),
    ]
