# Generated by Django 2.1.5 on 2020-04-30 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0031_auto_20200419_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='emergency_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lynx.EmergencyContact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='emergency_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lynx.EmergencyContact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='emergency_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lynx.EmergencyContact'),
            preserve_default=False,
        ),
    ]
