# Generated by Django 2.1.5 on 2020-04-30 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0032_auto_20200429_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lynx.EmergencyContact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact'),
        ),
        migrations.AlterField(
            model_name='email',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lynx.EmergencyContact'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lynx.EmergencyContact'),
        ),
    ]
