# Generated by Django 2.1.5 on 2020-05-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0034_auto_20200429_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='emergency_address_one',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='emergency_address_two',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='emergency_city',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='emergency_country',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='emergency_email',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='emergency_state',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='emergency_zip_code',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='phone_day',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='phone_other',
        ),
    ]
