# Generated by Django 2.1.5 on 2020-06-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0035_auto_20200430_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='performs_tasks',
            field=models.CharField(blank=True, choices=[('Visually', 'Visually'), ('Non-Visually', 'Non-Visually'), ('Both Visually and Non-Visually', 'Both Visually and Non-Visually')], max_length=150, null=True),
        ),
    ]
