# Generated by Django 2.1.5 on 2020-07-12 21:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lynx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0036_auto_20200621_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('note_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('bingo', models.BooleanField(blank=True, default=False)),
                ('access_news', models.BooleanField(blank=True, default=False)),
                ('programs', models.BooleanField(blank=True, default=False)),
                ('career_plus', models.BooleanField(blank=True, default=False)),
                ('other', models.TextField(null=True)),
                ('special_needs', models.TextField(null=True)),
                ('availability', models.TextField(null=True)),
                ('interests', models.TextField(null=True)),
                ('job_assignments', models.TextField(null=True)),
                ('personal_vehicle', models.BooleanField(blank=True, default=False)),
                ('vehicle_description', models.TextField(null=True)),
                ('time_sheets', models.TextField(null=True)),
                ('awards', models.TextField(null=True)),
                ('mandate_information', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='volunteer',
            new_name='volunteer_check',
        ),
        migrations.AddField(
            model_name='sipnote',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(lynx.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
