# Generated by Django 2.1.5 on 2020-08-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0039_auto_20200816_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='communication',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='communication_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Less than 54', 'Less than 54'), ('55-64', '55-54'), ('65-74', '65-74'), ('75-84', '75-84'), ('84+', '84+')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('American Indian/Alaska Native', 'American Indian/Alaska Native'), ('Asian', 'Asian'), ('Black/African American', 'Black/African American'), ('Hispanic/Latino', 'Hispanic/Latino'), ('Native Hawaiian/Other Pacific Islander', 'Native Hawaiian/Other Pacific Islander'), ('White', 'White'), ('Other', 'Other'), ('Did Not Disclose', 'Did Not Disclose')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('Private Residence', 'Private Residence'), ('Community Residential', 'Community Residential'), ('Assisted Living', 'Assisted Living'), ('Skilled Nursing Care', 'Skilled Nursing Care'), ('Senior Living', 'Senior Living'), ('Homeless', 'Homeless')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sipnote',
            name='class_hours',
            field=models.FloatField(blank=True, choices=[(0.25, '15 Minutes'), (0.5, '30 Minutes'), (0.75, '45 Minutes'), (1, '1 Hour'), (1.25, '1 Hour 15 Minutes'), (1.5, '1 Hour 30 Minutes'), (1.75, '1 Hour 45 Minutes'), (2, '2 Hours'), (2.25, '2 Hours 15 Minutes'), (2.5, '2 Hours 30 Minutes'), (2.75, '2 Hours 45 Minutes'), (3, '3 Hours'), (3.25, '3 Hours 15 Minutes'), (3.5, '3 Hours 30 Minutes'), (3.75, '3 Hours 45 Minutes'), (4, '4 Hours'), (4.25, '4 Hours 15 Minutes'), (4.5, '4 Hours 30 Minutes'), (4.75, '4 Hours 45 Minutes'), (5, '5 Hours'), (5.25, '5 Hours 15 Minutes'), (5.5, '5 Hours 30 Minutes'), (5.75, '5 Hours 45 Minutes'), (6, '6 Hours'), (6.25, '6 Hours 15 Minutes'), (6.5, '6 Hours 30 Minutes'), (6.75, '6 Hours 45 Minutes'), (7, '7 Hours'), (7.25, '7 Hours 15 Minutes'), (7.5, '7 Hours 30 Minutes'), (7.75, '7 Hours 45 Minutes'), (8, '8 Hours')], null=True),
        ),
    ]
