# Generated by Django 2.1.5 on 2020-09-13 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lynx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0040_auto_20200823_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('at_services', models.BooleanField(blank=True, default=False)),
                ('independent_living', models.BooleanField(blank=True, default=False)),
                ('orientation', models.BooleanField(blank=True, default=False)),
                ('communications', models.BooleanField(blank=True, default=False)),
                ('dls', models.BooleanField(blank=True, default=False)),
                ('advocacy', models.BooleanField(blank=True, default=False)),
                ('counseling', models.BooleanField(blank=True, default=False)),
                ('information', models.BooleanField(blank=True, default=False)),
                ('other_services', models.BooleanField(blank=True, default=False)),
                ('plan_name', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_progress', models.CharField(blank=True, choices=[('Plan not complete', 'Plan not complete'), ('Plan complete, feeling more confident in ability to maintain living situation', 'Plan complete, feeling more confident in ability to maintain living situation'), ('Plan complete, no difference in ability to maintain living situation', 'Plan complete, no difference in ability to maintain living situation'), ('Plan complete, feeling less confident in ability to maintain living situation', 'Plan complete, feeling less confident in ability to maintain living situation')], max_length=150, null=True)),
                ('assessment', models.CharField(blank=True, choices=[('Not assessed', 'Not assessed'), ('Assessed, improved independence', 'Assessed, improved independence'), ('Assessed, maintained independence', 'Assessed, maintained independence'), ('Assessed, decreased independence', 'Assessed, decreased independence')], max_length=150, null=True)),
                ('plan_start', models.DateField(null=True)),
                ('plan_end', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(lynx.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='intake',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander'), ('White', 'White'), ('Other', 'Other'), ('Did not self identify Race', 'Did not self identify Race')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sipnote',
            name='sip_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lynx.SipPlan'),
        ),
    ]
