# Generated by Django 2.1.5 on 2020-09-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0041_auto_20200913_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipplan',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sipplan',
            name='plan_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sipplan',
            name='plan_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
