# Generated by Django 2.1.5 on 2020-09-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0043_auto_20200913_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipplan',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='sipplan',
            name='plan_progress',
        ),
        migrations.AddField(
            model_name='sipplan',
            name='at_outcomes',
            field=models.CharField(blank=True, choices=[('Not assessed', 'Not assessed'), ('Assessed, improved independence', 'Assessed, improved independence'), ('Assessed, maintained independence', 'Assessed, maintained independence'), ('Assessed, decreased independence', 'Assessed, decreased independence')], default='Not assessed', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='community_plan_progress',
            field=models.CharField(blank=True, choices=[('Plan not complete', 'Plan not complete'), ('Plan complete, feeling more confident in ability to maintain living situation', 'Plan complete, feeling more confident in ability to maintain living situation'), ('Plan complete, no difference in ability to maintain living situation', 'Plan complete, no difference in ability to maintain living situation'), ('Plan complete, feeling less confident in ability to maintain living situation', 'Plan complete, feeling less confident in ability to maintain living situation')], default='Plan not complete', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='ila_outcomes',
            field=models.CharField(blank=True, choices=[('Not assessed', 'Not assessed'), ('Assessed, improved independence', 'Assessed, improved independence'), ('Assessed, maintained independence', 'Assessed, maintained independence'), ('Assessed, decreased independence', 'Assessed, decreased independence')], default='Not assessed', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='living_plan_progress',
            field=models.CharField(blank=True, choices=[('Plan not complete', 'Plan not complete'), ('Plan complete, feeling more confident in ability to maintain living situation', 'Plan complete, feeling more confident in ability to maintain living situation'), ('Plan complete, no difference in ability to maintain living situation', 'Plan complete, no difference in ability to maintain living situation'), ('Plan complete, feeling less confident in ability to maintain living situation', 'Plan complete, feeling less confident in ability to maintain living situation')], default='Plan not complete', max_length=150, null=True),
        ),
    ]
