# Generated by Django 2.1.5 on 2020-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0044_auto_20200920_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipnote',
            name='quarter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='referred_by',
            field=models.CharField(blank=True, choices=[('DOR', 'DOR'), ('Alta', 'Alta'), ('Veterans Administration', 'Veterans Administration'), ('Physician', 'Physician'), ('Family or Friend', 'Family or Friend'), ('Senior Program', 'Senior Program'), ('Assisted Living Facility', 'Assisted Living Facility'), ('Nursing Home', 'Nursing Home'), ('Independent Living Center', 'Independent Living Center'), ('Self-Referral', 'Self-Referral'), ('Other', 'Other')], max_length=250, null=True),
        ),
    ]
