# Generated by Django 2.1.5 on 2020-10-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0045_auto_20201011_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipnote',
            name='quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
