# Generated by Django 2.1.5 on 2020-10-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0047_intakenote_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='outside_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outside_agent', to='lynx.Contact'),
        ),
    ]
