# Generated by Django 2.1.5 on 2020-10-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0048_auto_20201018_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='billingname',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='BillingName',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
