# Generated by Django 2.1.5 on 2020-10-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0049_auto_20201018_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipnote',
            name='instructor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
