# Generated by Django 2.1.5 on 2020-10-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0050_sipnote_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='payment_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lynx.OutsideAgency'),
        ),
    ]
