# Generated by Django 2.1.5 on 2020-11-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0052_auto_20201020_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Less than 54', 'Less than 54'), ('55-64', '55-64'), ('65-74', '65-74'), ('75-84', '75-84'), ('84+', '84+')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sipplan',
            name='plan_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
