# Generated by Django 2.1.5 on 2020-11-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0053_auto_20201101_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outsideagency',
            old_name='contact',
            new_name='contact_name',
        ),
    ]
