# Generated by Django 2.1.5 on 2020-11-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0054_auto_20201106_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideagency',
            name='contact',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact'),
            preserve_default=False,
        ),
    ]
