# Generated by Django 2.2.17 on 2020-11-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0055_outsideagency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('intake_date', models.DateField(blank=True, null=True)),
                ('age_group', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'lynx_contactinfoview',
                'managed': False,
            },
        ),
    ]
