# Generated by Django 2.2.17 on 2021-01-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0056_contactinfoview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipplan',
            name='plan_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
