# Generated by Django 2.2.17 on 2021-01-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0059_historicaladdress_historicalauthorization_historicalcontact_historicalcontactinfoview_historicalemai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], max_length=25, null=True),
        ),
    ]
