# Generated by Django 2.2.17 on 2021-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0063_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='access_news',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='bingo',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='career_plus',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='job_assignments',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='mandate_information',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='other',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='personal_vehicle',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='special_needs',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='time_sheets',
        ),
        migrations.RemoveField(
            model_name='historicalvolunteer',
            name='vehicle_description',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='access_news',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='bingo',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='career_plus',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='job_assignments',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='mandate_information',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='other',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='personal_vehicle',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='special_needs',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='time_sheets',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='vehicle_description',
        ),
        migrations.AddField(
            model_name='historicalvolunteer',
            name='volunteer_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
