# Generated by Django 2.2.17 on 2021-05-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0064_auto_20210502_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvolunteer',
            old_name='note_date',
            new_name='volunteer_date',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='note_date',
            new_name='volunteer_date',
        ),
        migrations.AddField(
            model_name='historicalvolunteer',
            name='volunteer_type',
            field=models.CharField(blank=True, choices=[('Access News', 'Access News'), ('Core', 'Core'), ('SIP', 'SIP')], max_length=150),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(blank=True, choices=[('Access News', 'Access News'), ('Core', 'Core'), ('SIP', 'SIP')], max_length=150),
        ),
    ]
