# Generated by Django 2.2.17 on 2021-07-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0065_auto_20210502_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalintake',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Less than 54', 'Less than 54'), ('55-64', '55-64'), ('65-74', '65-74'), ('75-84', '75-84'), ('85 and older', '85 and older')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalintake',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander'), ('White', 'White'), ('Other', 'Other'), ('Did not self identify Race', 'Did not self identify Race'), ('Two or More Races', 'Two or More Races')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalintake',
            name='referred_by',
            field=models.CharField(blank=True, choices=[('DOR', 'DOR'), ('Alta', 'Alta'), ('Veterans Administration', 'Veterans Administration'), ('Family or Friend', 'Family or Friend'), ('Senior Program', 'Senior Program'), ('Assisted Living Facility', 'Assisted Living Facility'), ('Nursing Home', 'Nursing Home'), ('Independent Living Center', 'Independent Living Center'), ('Self-Referral', 'Self-Referral'), ('Physician/ Medical Provider', 'Physician/ Medical Provider'), ('Eye Care Provider', 'Eye Care Provider'), ('Other', 'Other')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsipplan',
            name='at_outcomes',
            field=models.CharField(blank=True, choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsipplan',
            name='ila_outcomes',
            field=models.CharField(blank=True, choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvolunteer',
            name='volunteer_hours',
            field=models.FloatField(blank=True, choices=[(0.25, '15 Minutes'), (0.5, '30 Minutes'), (0.75, '45 Minutes'), (1, '1 Hour'), (1.25, '1 Hour 15 Minutes'), (1.5, '1 Hour 30 Minutes'), (1.75, '1 Hour 45 Minutes'), (2, '2 Hours'), (2.25, '2 Hours 15 Minutes'), (2.5, '2 Hours 30 Minutes'), (2.75, '2 Hours 45 Minutes'), (3, '3 Hours'), (3.25, '3 Hours 15 Minutes'), (3.5, '3 Hours 30 Minutes'), (3.75, '3 Hours 45 Minutes'), (4, '4 Hours'), (4.25, '4 Hours 15 Minutes'), (4.5, '4 Hours 30 Minutes'), (4.75, '4 Hours 45 Minutes'), (5, '5 Hours'), (5.25, '5 Hours 15 Minutes'), (5.5, '5 Hours 30 Minutes'), (5.75, '5 Hours 45 Minutes'), (6, '6 Hours'), (6.25, '6 Hours 15 Minutes'), (6.5, '6 Hours 30 Minutes'), (6.75, '6 Hours 45 Minutes'), (7, '7 Hours'), (7.25, '7 Hours 15 Minutes'), (7.5, '7 Hours 30 Minutes'), (7.75, '7 Hours 45 Minutes'), (8, '8 Hours')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalvolunteer',
            name='volunteer_type',
            field=models.CharField(blank=True, choices=[('Access News', 'Access News'), ('Core', 'Core'), ('SIP', 'SIP'), ('CareersPLUS', 'CareersPLUS'), ('Agency', 'Agency')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intake',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Less than 54', 'Less than 54'), ('55-64', '55-64'), ('65-74', '65-74'), ('75-84', '75-84'), ('85 and older', '85 and older')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander'), ('White', 'White'), ('Other', 'Other'), ('Did not self identify Race', 'Did not self identify Race'), ('Two or More Races', 'Two or More Races')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='referred_by',
            field=models.CharField(blank=True, choices=[('DOR', 'DOR'), ('Alta', 'Alta'), ('Veterans Administration', 'Veterans Administration'), ('Family or Friend', 'Family or Friend'), ('Senior Program', 'Senior Program'), ('Assisted Living Facility', 'Assisted Living Facility'), ('Nursing Home', 'Nursing Home'), ('Independent Living Center', 'Independent Living Center'), ('Self-Referral', 'Self-Referral'), ('Physician/ Medical Provider', 'Physician/ Medical Provider'), ('Eye Care Provider', 'Eye Care Provider'), ('Other', 'Other')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sipplan',
            name='at_outcomes',
            field=models.CharField(blank=True, choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sipplan',
            name='ila_outcomes',
            field=models.CharField(blank=True, choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_hours',
            field=models.FloatField(blank=True, choices=[(0.25, '15 Minutes'), (0.5, '30 Minutes'), (0.75, '45 Minutes'), (1, '1 Hour'), (1.25, '1 Hour 15 Minutes'), (1.5, '1 Hour 30 Minutes'), (1.75, '1 Hour 45 Minutes'), (2, '2 Hours'), (2.25, '2 Hours 15 Minutes'), (2.5, '2 Hours 30 Minutes'), (2.75, '2 Hours 45 Minutes'), (3, '3 Hours'), (3.25, '3 Hours 15 Minutes'), (3.5, '3 Hours 30 Minutes'), (3.75, '3 Hours 45 Minutes'), (4, '4 Hours'), (4.25, '4 Hours 15 Minutes'), (4.5, '4 Hours 30 Minutes'), (4.75, '4 Hours 45 Minutes'), (5, '5 Hours'), (5.25, '5 Hours 15 Minutes'), (5.5, '5 Hours 30 Minutes'), (5.75, '5 Hours 45 Minutes'), (6, '6 Hours'), (6.25, '6 Hours 15 Minutes'), (6.5, '6 Hours 30 Minutes'), (6.75, '6 Hours 45 Minutes'), (7, '7 Hours'), (7.25, '7 Hours 15 Minutes'), (7.5, '7 Hours 30 Minutes'), (7.75, '7 Hours 45 Minutes'), (8, '8 Hours')], null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(blank=True, choices=[('Access News', 'Access News'), ('Core', 'Core'), ('SIP', 'SIP'), ('CareersPLUS', 'CareersPLUS'), ('Agency', 'Agency')], max_length=150),
        ),
    ]
