# Generated by Django 2.2.17 on 2021-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0066_auto_20210724_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsipplan',
            name='support_services',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='support_services',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
