# Generated by Django 2.2.17 on 2021-08-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0067_auto_20210724_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='payment_source',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='payment_source',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
