# Generated by Django 2.2.17 on 2021-10-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0068_auto_20210808_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalintake',
            name='payment_source',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='payment_source',
        ),
        migrations.AddField(
            model_name='historicalintake',
            name='outside_agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.Contact'),
        ),
        migrations.AddField(
            model_name='intake',
            name='outside_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_outside_agent', to='lynx.Contact'),
        ),
    ]
