# Generated by Django 2.2.17 on 2021-10-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0069_auto_20211013_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalintake',
            old_name='outside_agency',
            new_name='payment_source',
        ),
        migrations.RenameField(
            model_name='intake',
            old_name='outside_agency',
            new_name='payment_source',
        ),
    ]
