# Generated by Django 2.2.17 on 2021-11-01 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lynx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0070_auto_20211013_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalintake',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicalintake',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='historicalintake',
            name='user',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='created',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='user',
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(blank=True, choices=[('P or M Dose 2', 'P or M Dose 2'), ('J&J Single', 'J&J Single'), ('Booster', 'Booster')], max_length=25, null=True)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('vaccine_note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(lynx.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
