# Generated by Django 2.2.17 on 2022-02-14 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lynx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0071_auto_20211031_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsipplan',
            name='plan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='plan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalintake',
            name='degree',
            field=models.CharField(blank=True, choices=[('Totally Blind (NP or NLP)', 'Totally Blind (NP or NLP)'), ('Legally Blind', 'Legally Blind'), ('Severe Vision Impairment', 'Severe Vision Impairment'), ('Light Perception Only', 'Light Perception Only'), ('Low Vision', 'Low Vision')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='degree',
            field=models.CharField(blank=True, choices=[('Totally Blind (NP or NLP)', 'Totally Blind (NP or NLP)'), ('Legally Blind', 'Legally Blind'), ('Severe Vision Impairment', 'Severe Vision Impairment'), ('Light Perception Only', 'Light Perception Only'), ('Low Vision', 'Low Vision')], max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.Contact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(lynx.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
