# Generated by Django 2.2.17 on 2022-02-21 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0072_auto_20220213_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructors',
            field=models.ManyToManyField(related_name='instructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
