# Generated by Django 2.2.17 on 2022-03-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0073_auto_20220220_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='instructors',
            new_name='instructor',
        ),
    ]
