# Generated by Django 2.2.17 on 2022-03-18 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0074_auto_20220317_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='instructor',
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(default=210, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
