# Generated by Django 2.2.17 on 2022-03-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0076_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
