# Generated by Django 2.2.17 on 2022-08-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0077_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalintake',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalintake',
            name='secondary_eye_condition',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='secondary_eye_condition',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
