# Generated by Django 2.2.17 on 2022-11-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0079_auto_20221106_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='status',
            new_name='assignment_status',
        ),
    ]
