# Generated by Django 2.2.17 on 2022-11-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0080_auto_20221106_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
