# Generated by Django 4.2 on 2023-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0081_auto_20221127_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaladdress',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical address', 'verbose_name_plural': 'historical Addresses'},
        ),
        migrations.AlterModelOptions(
            name='historicalauthorization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical authorization', 'verbose_name_plural': 'historical authorizations'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontact',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact', 'verbose_name_plural': 'historical contacts'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontactinfoview',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact info view', 'verbose_name_plural': 'historical contact info views'},
        ),
        migrations.AlterModelOptions(
            name='historicalemail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical email', 'verbose_name_plural': 'historical emails'},
        ),
        migrations.AlterModelOptions(
            name='historicalemergencycontact',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical emergency contact', 'verbose_name_plural': 'historical emergency contacts'},
        ),
        migrations.AlterModelOptions(
            name='historicalintake',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical intake', 'verbose_name_plural': 'historical intakes'},
        ),
        migrations.AlterModelOptions(
            name='historicalintakenote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical intake note', 'verbose_name_plural': 'historical intake notes'},
        ),
        migrations.AlterModelOptions(
            name='historicalintakeservicearea',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical intake service area', 'verbose_name_plural': 'historical intake service areas'},
        ),
        migrations.AlterModelOptions(
            name='historicallessonnote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lesson note', 'verbose_name_plural': 'historical lesson notes'},
        ),
        migrations.AlterModelOptions(
            name='historicaloutsideagency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical outside agency', 'verbose_name_plural': 'historical Outside Agencies'},
        ),
        migrations.AlterModelOptions(
            name='historicalphone',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical phone', 'verbose_name_plural': 'historical phones'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogressreport',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical progress report', 'verbose_name_plural': 'historical progress reports'},
        ),
        migrations.AlterModelOptions(
            name='historicalsipnote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sip note', 'verbose_name_plural': 'historical sip notes'},
        ),
        migrations.AlterModelOptions(
            name='historicalsipplan',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sip plan', 'verbose_name_plural': 'historical sip plans'},
        ),
        migrations.AlterModelOptions(
            name='historicalvolunteer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical volunteer', 'verbose_name_plural': 'historical volunteers'},
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalauthorization',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactinfoview',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemail',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencycontact',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalintake',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalintakenote',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalintakeservicearea',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallessonnote',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaloutsideagency',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalphone',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprogressreport',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsipnote',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsipplan',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvolunteer',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
