# Generated by Django 4.2 on 2023-10-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0086_sip1854plan_sip1854note_historicalsip1854plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sip1854_client',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='sip1854_client',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalcontactinfoview',
            name='sip1854_client',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
