# Generated by Django 4.2 on 2024-02-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0088_alter_historicalintake_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsip1854plan',
            name='employment_outcomes',
            field=models.CharField(blank=True, choices=[('Not Interested in Employment', 'Not Interested in Employment'), ('Less Likely to Seek Employment', 'Less Likely to Seek Employment'), ('Unsure about Seeking Employment', 'Unsure about Seeking Employment'), ('More Likely to Seek Employment', 'More Likely to Seek Employment')], default='Not Interested in Employment', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalsipplan',
            name='employment_outcomes',
            field=models.CharField(blank=True, choices=[('Not Interested in Employment', 'Not Interested in Employment'), ('Less Likely to Seek Employment', 'Less Likely to Seek Employment'), ('Unsure about Seeking Employment', 'Unsure about Seeking Employment'), ('More Likely to Seek Employment', 'More Likely to Seek Employment')], default='Not Interested in Employment', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sip1854plan',
            name='employment_outcomes',
            field=models.CharField(blank=True, choices=[('Not Interested in Employment', 'Not Interested in Employment'), ('Less Likely to Seek Employment', 'Less Likely to Seek Employment'), ('Unsure about Seeking Employment', 'Unsure about Seeking Employment'), ('More Likely to Seek Employment', 'More Likely to Seek Employment')], default='Not Interested in Employment', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sipplan',
            name='employment_outcomes',
            field=models.CharField(blank=True, choices=[('Not Interested in Employment', 'Not Interested in Employment'), ('Less Likely to Seek Employment', 'Less Likely to Seek Employment'), ('Unsure about Seeking Employment', 'Unsure about Seeking Employment'), ('More Likely to Seek Employment', 'More Likely to Seek Employment')], default='Not Interested in Employment', max_length=150, null=True),
        ),
    ]
