# Generated by Django 4.2 on 2024-04-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0089_historicalsip1854plan_employment_outcomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='program',
            field=models.CharField(max_length=25, default='SIP'),
        ),
        migrations.RunSQL("UPDATE lynx_assignment SET program = 'SIP';"),
    ]
