# Generated by Django 4.2 on 2024-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0090_auto_20240417_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip1854assignment',
            name='program',
            field=models.CharField(max_length=25, default='1854'),
        ),
        migrations.RunSQL("UPDATE lynx_sip1854assignment SET program = '1854';"),
    ]
