# Generated by Django 4.2 on 2024-04-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0092_historicalassignment_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='program',
            field=models.CharField(choices=[('SIP', 'SIP'), ('1854', '1854')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='program',
            field=models.CharField(choices=[('SIP', 'SIP'), ('1854', '1854')], max_length=25, null=True),
        ),
    ]
