# Generated by Django 4.2 on 2024-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0094_alter_assignment_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='program',
            field=models.CharField(choices=[('SIP', 'SIP'), ('1854', '1854')], default='SIP', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='program',
            field=models.CharField(choices=[('SIP', 'SIP'), ('1854', '1854')], default='1854', max_length=25),
            preserve_default=False,
        ),
    ]
