# Generated by Django 4.2 on 2024-05-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0096_alter_assignment_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Returning', 'Returning')], default='New', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='priority',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Returning', 'Returning')], default='New', max_length=25, null=True),
        ),
    ]
