# Generated by Django 4.2 on 2024-05-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0098_historicalsip1854assignment_priority_and_more'),
    ]

    # Idempotent   SQL   query  to   "merge   assignments"
    # (copy  all  lines from  `lynx_sip1854assignment`  to
    # `lynx_assignment`).
    operations = [
        migrations.RunSQL("""
            INSERT INTO lynx_assignment ("assignment_date", "assignment_status", "contact_id", "created", "instructor_id", "modified", "note", "program", "user_id", "priority")
            SELECT                       "assignment_date", "assignment_status", "contact_id", "created", "instructor_id", "modified", "note", "program", "user_id", "priority" 
            FROM lynx_sip1854assignment
            WHERE NOT EXISTS (
                SELECT 1 FROM lynx_assignment
                WHERE lynx_assignment.assignment_date = lynx_sip1854assignment.assignment_date
                AND lynx_assignment.assignment_status = lynx_sip1854assignment.assignment_status
                AND lynx_assignment.contact_id        = lynx_sip1854assignment.contact_id
                AND lynx_assignment.created           = lynx_sip1854assignment.created
                AND lynx_assignment.instructor_id     = lynx_sip1854assignment.instructor_id
                AND lynx_assignment.modified          = lynx_sip1854assignment.modified
                AND lynx_assignment.note              = lynx_sip1854assignment.note
                AND lynx_assignment.program           = lynx_sip1854assignment.program
                AND lynx_assignment.user_id           = lynx_sip1854assignment.user_id
                AND lynx_assignment.priority          = lynx_sip1854assignment.priority
            );
        """),
    ]
