# Generated by Django 4.2 on 2024-08-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0099_auto_20240523_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sip1854assignment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='sip1854assignment',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='sip1854assignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalSip1854Assignment',
        ),
        migrations.DeleteModel(
            name='Sip1854Assignment',
        ),
    ]
