# Generated by Django 4.2 on 2024-08-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0100_remove_sip1854assignment_contact_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS lynx_intake_1;
            DROP TABLE IF EXISTS lynx_intake_2;
            DROP TABLE IF EXISTS lynx_intakenote_1;
            DROP TABLE IF EXISTS lynx_lessonnote_old;
            DROP TABLE IF EXISTS lynx_lessonnote_pre_at;
            DROP TABLE IF EXISTS lynx_sipnote_preupdate;
            """
        ),
    ]
