# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models

# NOTE "service delivery type" === "plan type"
#      ----------------------------------------------------
#      On the front-end, this is called  "plan  type",  for
#      historical and  beurocratic  reasons.  Beaurocratic:
#      DOR wants lots of plans, and  having  one  plan  per
#      year per client per service  delivery  type  is  the
#      sweet spot. Historical: the original  implementation
#      is flawed, and every user now  thinks  of  these  as
#      "plan types". Damage done.

# https://wiki.postgresql.org/wiki/CTEReadme
def add_initial_delivery_types(apps, schema_editor):
    OIBServiceDeliveryType = apps.get_model('lynx', 'OIBServiceDeliveryType')
    OIBServiceDeliveryType.objects.bulk_create([
        OIBServiceDeliveryType(id=0, parent_id=None, oib_service_delivery_type='ROOT'),
        OIBServiceDeliveryType(id=1, parent_id=0, oib_service_delivery_type='in-home'),
        OIBServiceDeliveryType(id=2, parent_id=0, oib_service_delivery_type='support group'),
        OIBServiceDeliveryType(id=3, parent_id=0, oib_service_delivery_type='training seminar'),
        OIBServiceDeliveryType(id=4, parent_id=0, oib_service_delivery_type='community integration'),
        OIBServiceDeliveryType(id=5, parent_id=0, oib_service_delivery_type='retreat'),
        OIBServiceDeliveryType(id=6, parent_id=2, oib_service_delivery_type='Spanish Support Group'),
        OIBServiceDeliveryType(id=7, parent_id=2, oib_service_delivery_type='Asian Support Group'),
        OIBServiceDeliveryType(id=8, parent_id=2, oib_service_delivery_type='BASS'),
        OIBServiceDeliveryType(id=9, parent_id=0, oib_service_delivery_type='one-time event'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0101-1_add_oibprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIBServiceDeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('oib_service_delivery_type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(add_initial_delivery_types),
    ]
