# Generated by Django 4.2 on 2024-09-15 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lynx.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0101_delete_unused_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('at_services', models.BooleanField(blank=True, default=False)),
                ('independent_living', models.BooleanField(blank=True, default=False)),
                ('orientation', models.BooleanField(blank=True, default=False)),
                ('communications', models.BooleanField(blank=True, default=False)),
                ('dls', models.BooleanField(blank=True, default=False)),
                ('advocacy', models.BooleanField(blank=True, default=False)),
                ('counseling', models.BooleanField(blank=True, default=False)),
                ('information', models.BooleanField(blank=True, default=False)),
                ('other_services', models.BooleanField(blank=True, default=False)),
                ('support_services', models.BooleanField(blank=True, default=False)),
                ('plan_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(choices=[('SIP', 'SIP'), ('1854', '1854')], default='SIP', max_length=25)),
                ('living_plan_progress', models.CharField(choices=[('Plan not complete', 'Plan not complete'), ('Plan complete, feeling more confident in ability to maintain living situation', 'Plan complete, feeling more confident in ability to maintain living situation'), ('Plan complete, no difference in ability to maintain living situation', 'Plan complete, no difference in ability to maintain living situation'), ('Plan complete, feeling less confident in ability to maintain living situation', 'Plan complete, feeling less confident in ability to maintain living situation')], default='Plan not complete', max_length=150)),
                ('community_plan_progress', models.CharField(choices=[('Plan not complete', 'Plan not complete'), ('Plan complete, feeling more confident in ability to maintain living situation', 'Plan complete, feeling more confident in ability to maintain living situation'), ('Plan complete, no difference in ability to maintain living situation', 'Plan complete, no difference in ability to maintain living situation'), ('Plan complete, feeling less confident in ability to maintain living situation', 'Plan complete, feeling less confident in ability to maintain living situation')], default='Plan not complete', max_length=150)),
                ('employment_outcomes', models.CharField(choices=[('Not Interested in Employment', 'Not Interested in Employment'), ('Less Likely to Seek Employment', 'Less Likely to Seek Employment'), ('Unsure about Seeking Employment', 'Unsure about Seeking Employment'), ('More Likely to Seek Employment', 'More Likely to Seek Employment')], default='Not Interested in Employment', max_length=150)),
                ('at_outcomes', models.CharField(choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150)),
                ('ila_outcomes', models.CharField(choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.contact')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(lynx.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPlan',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('at_services', models.BooleanField(blank=True, default=False)),
                ('independent_living', models.BooleanField(blank=True, default=False)),
                ('orientation', models.BooleanField(blank=True, default=False)),
                ('communications', models.BooleanField(blank=True, default=False)),
                ('dls', models.BooleanField(blank=True, default=False)),
                ('advocacy', models.BooleanField(blank=True, default=False)),
                ('counseling', models.BooleanField(blank=True, default=False)),
                ('information', models.BooleanField(blank=True, default=False)),
                ('other_services', models.BooleanField(blank=True, default=False)),
                ('support_services', models.BooleanField(blank=True, default=False)),
                ('plan_date', models.DateField()),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(choices=[('SIP', 'SIP'), ('1854', '1854')], default='SIP', max_length=25)),
                ('living_plan_progress', models.CharField(choices=[('Plan not complete', 'Plan not complete'), ('Plan complete, feeling more confident in ability to maintain living situation', 'Plan complete, feeling more confident in ability to maintain living situation'), ('Plan complete, no difference in ability to maintain living situation', 'Plan complete, no difference in ability to maintain living situation'), ('Plan complete, feeling less confident in ability to maintain living situation', 'Plan complete, feeling less confident in ability to maintain living situation')], default='Plan not complete', max_length=150)),
                ('community_plan_progress', models.CharField(choices=[('Plan not complete', 'Plan not complete'), ('Plan complete, feeling more confident in ability to maintain living situation', 'Plan complete, feeling more confident in ability to maintain living situation'), ('Plan complete, no difference in ability to maintain living situation', 'Plan complete, no difference in ability to maintain living situation'), ('Plan complete, feeling less confident in ability to maintain living situation', 'Plan complete, feeling less confident in ability to maintain living situation')], default='Plan not complete', max_length=150)),
                ('employment_outcomes', models.CharField(choices=[('Not Interested in Employment', 'Not Interested in Employment'), ('Less Likely to Seek Employment', 'Less Likely to Seek Employment'), ('Unsure about Seeking Employment', 'Unsure about Seeking Employment'), ('More Likely to Seek Employment', 'More Likely to Seek Employment')], default='Not Interested in Employment', max_length=150)),
                ('at_outcomes', models.CharField(choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150)),
                ('ila_outcomes', models.CharField(choices=[('Not assessed', 'Not assessed'), ('Assessed with improved independence', 'Assessed with improved independence'), ('Assessed and maintained independence', 'Assessed and maintained independence'), ('Assessed with decreased independence', 'Assessed with decreased independence')], default='Not assessed', max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.contact')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plan',
                'verbose_name_plural': 'historical plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
