# Generated by Django 4.2 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def add_initial_delivery_types(apps, schema_editor):
    SipServiceDeliveryType = apps.get_model('lynx', 'SipServiceDeliveryType')
    SipServiceDeliveryType.objects.bulk_create([
        SipServiceDeliveryType(id=0, parent_id=None, name='ROOT'),
        SipServiceDeliveryType(id=1, parent_id=0, name='in-home'),
        SipServiceDeliveryType(id=2, parent_id=0, name='support group'),
        SipServiceDeliveryType(id=3, parent_id=0, name='training seminar'),
        SipServiceDeliveryType(id=4, parent_id=0, name='community integration'),
        SipServiceDeliveryType(id=5, parent_id=0, name='retreat'),
        SipServiceDeliveryType(id=6, parent_id=2, name='Spanish Support Group'),
        SipServiceDeliveryType(id=7, parent_id=2, name='Asian Support Group'),
        SipServiceDeliveryType(id=8, parent_id=2, name='BASS'),
        SipServiceDeliveryType(id=9, parent_id=0, name='one-time event'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0102_add_sipserviceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipServiceDeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(add_initial_delivery_types),

        migrations.CreateModel(
            name='HistoricalSipServiceDeliveryType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sip service delivery type',
                'verbose_name_plural': 'historical sip service delivery types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
