# Generated by Django 4.2 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime, date


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0102_add_oibservicedeliverytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIBServiceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #      =========================================
                # NOTE 1 service delivery type per service event
                #      =========================================
                #      There was  a  many-to-many  relationship  between
                #      service events and service delivery types, but
                #      because  I  have  never  seen  a
                #      service  event  delivered  by  multiple   service
                #      delivery types,  decided  to  simply  include  it
                #      here.
                #     ==================
                # NOTE on_delete=PROTECT
                #     ==================
                #     service  events  are  one  of  the  most   important
                #     entities; it needs to preserved for  audit  reasons.
                #     Probably  adding  a  soft-delete  feature   to   the
                #     referenced tables would be a good idea.
                ('oib_service_delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibservicedeliverytype')),
                # NOTE See "0109_add_oibserviceeventcontact.py" for
                #      the diff between `organizer` and `OIBServiceEventContact.oib_program`
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibprogram')),
                ('date', models.DateField(blank=True, default=date.today)),
                # ('start_time', models.TimeField(blank=True, default="00:00:00")),
                # ('end_time', models.TimeField(blank=True, default="00:00:00")),
                ('length', models.DurationField(blank=True, default="00:00:00")),
                ('note', models.TextField(blank=True, default="")),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]