# Generated by Django 4.2 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def add_initial_services(apps, schema_editor):
    SipService = apps.get_model('lynx', 'SipService')
    SipService.objects.bulk_create([
        SipService(id=0, name='assistive technology devices and services'),
        SipService(id=1, name='orientation and mobility training'),
        SipService(id=2, name='communication skills training'),
        SipService(id=3, name='daily living skills training'),
        SipService(id=4, name='advocacy training'),
        SipService(id=5, name='adjustment counseling'),
        SipService(id=6, name='supportive services'),
        SipService(id=7, name='information and referral'),
        SipService(id=8, name='other IL/A services'),
        SipService(id=9, name='supportive services'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0103_add_sipservicedeliverytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(add_initial_services),

        migrations.CreateModel(
            name='HistoricalSipService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sip service',
                'verbose_name_plural': 'historical sip services',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
