# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models


def add_initial_services(apps, schema_editor):
    SipService = apps.get_model('lynx', 'SipService')
    SipService.objects.bulk_create([
        SipService(id=0, name='assistive technology devices and services'),
        SipService(id=1, name='orientation and mobility training'),
        SipService(id=2, name='communication skills training'),
        SipService(id=3, name='daily living skills training'),
        SipService(id=4, name='advocacy training'),
        SipService(id=5, name='adjustment counseling'),
        SipService(id=6, name='supportive services'),
        SipService(id=7, name='information and referral'),
        SipService(id=8, name='other IL/A services'),
        SipService(id=9, name='supportive services'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0103_add_sipserviceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(add_initial_services),
    ]
