# Generated by Django 4.2 on 2024-09-21 14:58

from django.db import migrations

def create_initial_service_delivery_types(apps, schema_editor):
    ServiceDeliveryType = apps.get_model('lynx', 'ServiceDeliveryType')
    initial_types = [
        "In-home",
        "Support Group",
        "Training Seminar",
        "Community Integration",
        "Retreat"
    ]
    for type_name in initial_types:
        ServiceDeliveryType.objects.create(name=type_name)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0103_add_SDT_and_SDST'),
    ]

    operations = [
        migrations.RunPython(create_initial_service_delivery_types),
    ]
