# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0104_add_oibservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIBServiceEventOIBService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oib_service_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibserviceevent')),
                ('oib_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibservice')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
