# Generated by Django 4.2 on 2024-09-21 17:41

from django.db import migrations

def create_initial_service_delivery_subtypes(apps, schema_editor):

    ServiceDeliverySubType = apps.get_model('lynx', 'ServiceDeliverySubType')

    ServiceDeliveryType    = apps.get_model('lynx', 'ServiceDeliveryType')
    support_group = ServiceDeliveryType.objects.filter( name="Support Group")[0]

    initial_types = [
        "BASS",
        "Asian Support Group",
        "Woodland Support Group",
        "Spanish Support Group",
        "Coffee and Connect"
    ]

    for subtype_name in initial_types:
        ServiceDeliverySubType.objects.create(
            name                  = subtype_name,
            is_one_time           = False,
            service_delivery_type = support_group
        )

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0104_add_initial_SDT_choices'),
    ]

    operations = [
        migrations.RunPython(create_initial_service_delivery_subtypes),
    ]
