# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0104_add_sipservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipServiceEventSipService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.sipserviceevent')),
                ('sip_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.sipservice')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
