# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models


def add_initial_roles(apps, schema_editor):
    SipServiceEventContactRole = apps.get_model('lynx', 'SipServiceEventContactRole')
    SipServiceEventContactRole.objects.bulk_create([
        SipServiceEventContactRole(id=0, name='participating_client'),
        SipServiceEventContactRole(id=1, name='presenter'),
        SipServiceEventContactRole(id=2, name='guest'),
        SipServiceEventContactRole(id=3, name='caregiver'),
        SipServiceEventContactRole(id=4, name='family member'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0105_add_sipserviceeventsipservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipServiceEventContactRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RunPython(add_initial_roles),
    ]
