# Generated by Django 4.2 on 2024-09-21 18:24

from django.db import migrations

def add_initial_services(apps, schema_editor):

    Service = apps.get_model('lynx', 'Service')

    initial_services = [
        "Assistive Technology Devices and Services",
        "Orientation & Mobility Training",
        "Communication Skills Training",
        "Daily Living Skills Training",
        "Advocacy Training",
        "Adjustment Counseling",
        "Information and Referral",
        "Other IL/A Services",
        "Supportive Services"
    ]

    for service in initial_services:
        Service.objects.create( name = service)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0106_add_service_table'),
    ]

    operations = [
        migrations.RunPython(add_initial_services),
    ]
