# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models


def add_initial_roles(apps, schema_editor):
    OIBServiceEventContactRole = apps.get_model('lynx', 'OIBServiceEventContactRole')
    OIBServiceEventContactRole.objects.bulk_create([
        OIBServiceEventContactRole(id=0, oib_service_event_contact_role='participating_client'),
        OIBServiceEventContactRole(id=1, oib_service_event_contact_role='presenter'),
        OIBServiceEventContactRole(id=2, oib_service_event_contact_role='guest'),
        OIBServiceEventContactRole(id=3, oib_service_event_contact_role='caregiver'),
        OIBServiceEventContactRole(id=4, oib_service_event_contact_role='family member'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0105_add_oibserviceeventoibservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIBServiceEventContactRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oib_service_event_contact_role', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(add_initial_roles),
    ]
