# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models


def add_initial_roles(apps, schema_editor):
    ServiceEventRole = apps.get_model('lynx', 'ServiceEventRole')
    ServiceEventRole.objects.bulk_create([
        ServiceEventRole(id=0, name='participant'),
        ServiceEventRole(id=1, name='facilitator'),
        ServiceEventRole(id=2, name='presenter'),
        ServiceEventRole(id=3, name='guest'),
        ServiceEventRole(id=4, name='caregiver'),
        ServiceEventRole(id=5, name='family member'),
        ServiceEventRole(id=6, name='entered by'),
        ServiceEventRole(id=7, name='switchboard'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0105_add_sipserviceeventsipservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEventRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RunPython(add_initial_roles),
    ]
