# Generated by Django 4.2 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0107_add_serviceeventrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipServiceEventInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.sipserviceevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_event_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.serviceeventrole')),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
