# Generated by Django 4.2 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0107_add_sipserviceeventcontactrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipServiceEventContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.sipserviceevent')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.contact')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.sipserviceeventcontactrole', default=0)),
                # All  clients  (should...)  exclusively   belong   to
                # **one** SIP program, so one SERVICE EVENT  can  only
                # be delivered under one SIP program per client.
                ('program', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lynx.sipprogram')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
