# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models


def add_initial_outcome_types(apps, schema_editor):
    OibOutcomeType = apps.get_model('lynx', 'OibOutcomeType')
    OibOutcomeType.objects.bulk_create([
        OibOutcomeType(id=0, oib_outcome_type='AT Goal Outcome'),
        OibOutcomeType(id=1, oib_outcome_type='IL/A Service Goal Outcome'),
        OibOutcomeType(id=2, oib_outcome_type='Living Situation Outcome'),
        OibOutcomeType(id=3, oib_outcome_type='Home and Community Involvement Outcome'),
        OibOutcomeType(id=4, oib_outcome_type='Employment Outcome'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0109_add_oibserviceeventcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OibOutcomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oib_outcome_type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(add_initial_outcome_types),
    ]
