# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models


def add_initial_outcome_choice(apps, schema_editor):
    OibOutcomeChoice = apps.get_model('lynx', 'OibOutcomeChoice')
    OibOutcomeChoice.objects.bulk_create([
        OibOutcomeChoice(id=0, name="Plan not complete"),
        OibOutcomeChoice(id=1, name="Plan complete, feeling more confident in ability to maintain living situation"),
        OibOutcomeChoice(id=2, name="Plan complete, no difference in ability to maintain living situation"),
        OibOutcomeChoice(id=3, name="Plan complete, feeling less confident in ability to maintain living situation"),
        OibOutcomeChoice(id=4, name="Not assessed"),
        OibOutcomeChoice(id=5, name="Assessed with improved independence"),
        OibOutcomeChoice(id=6, name="Assessed and maintained independence"),
        OibOutcomeChoice(id=7, name="Assessed with decreased independence"),
        OibOutcomeChoice(id=8, name="Not Interested in Employment"),
        OibOutcomeChoice(id=9, name="Less Likely to Seek Employment"),
        OibOutcomeChoice(id=10, name="Unsure about Seeking Employment"),
        OibOutcomeChoice(id=11, name="More Likely to Seek Employment"),
])

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0110_add_oiboutcometype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OibOutcomeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(add_initial_outcome_choice),
    ]
