# Generated by Django 4.2 on 2025-01-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0112_add_oiboutcometypechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OibOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.contact')),
                ('oib_outcome_type_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.oiboutcometypechoice')),
            ],
        ),
    ]
