# Generated by Django 4.2 on 2025-01-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0114_add_oibserviceeventinstructorrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIBServiceEventInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibserviceevent')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                # Service event user roles will probably not be used,
                # but in case it is needed, it will be here.
                ('oib_service_event_instructor_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibserviceeventinstructorrole', default=0)),
                # No "program" field, like in  OIBServiceEventContact,
                # because instructors deliver services  in  every  SIP
                # program, so it doesn't make sense.
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
