# Generated by Django 4.2 on 2025-03-30 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lynx', '0116_alter_oiboutcome_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloibserviceeventinstructor',
            old_name='service_event',
            new_name='oib_service_event',
        ),
        migrations.RenameField(
            model_name='oibserviceeventinstructor',
            old_name='service_event',
            new_name='oib_service_event',
        ),
        migrations.RemoveField(
            model_name='historicaloibserviceevent',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='oibserviceevent',
            name='organizer',
        ),
        migrations.AddField(
            model_name='oiboutcomechoice',
            name='outcome_types',
            field=models.ManyToManyField(through='lynx.OibOutcomeTypeChoice', to='lynx.oiboutcometype'),
        ),
        migrations.AddField(
            model_name='oibserviceevent',
            name='contacts',
            field=models.ManyToManyField(through='lynx.OIBServiceEventContact', to='lynx.contact'),
        ),
        migrations.AddField(
            model_name='oibserviceevent',
            name='instructors',
            field=models.ManyToManyField(through='lynx.OIBServiceEventInstructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oibserviceevent',
            name='services',
            field=models.ManyToManyField(through='lynx.OIBServiceEventOIBService', to='lynx.oibservice'),
        ),
        migrations.AlterField(
            model_name='oibserviceevent',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_service_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='oiboutcometypechoice',
            constraint=models.UniqueConstraint(fields=('oib_outcome_type', 'oib_outcome_choice'), name='unique_oib_outcome_type_choice'),
        ),
        migrations.AddConstraint(
            model_name='oibserviceeventcontact',
            constraint=models.UniqueConstraint(fields=('oib_service_event', 'contact'), name='unique_oib_service_event_contact'),
        ),
        migrations.AddConstraint(
            model_name='oibserviceeventinstructor',
            constraint=models.UniqueConstraint(fields=('oib_service_event', 'instructor'), name='unique_oib_service_event_instructor'),
        ),
        migrations.AddConstraint(
            model_name='oibserviceeventoibservice',
            constraint=models.UniqueConstraint(fields=('oib_service_event', 'oib_service'), name='unique_oib_service_event_oib_service'),
        ),
    ]
