# Generated by Django 5.1.7 on 2025-08-15 22:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0117_rename_service_event_historicaloibserviceeventinstructor_oib_service_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloibserviceeventcontact',
            name='oib_program',
        ),
        migrations.RemoveField(
            model_name='oibserviceeventcontact',
            name='oib_program',
        ),
        migrations.CreateModel(
            name='HistoricalOIBServiceEventOIBProgram',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oib_program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.oibprogram')),
                ('oib_service_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.oibserviceevent')),
            ],
            options={
                'verbose_name': 'historical oib service event oib program',
                'verbose_name_plural': 'historical oib service event oib programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OIBServiceEventOIBProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('oib_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibprogram')),
                ('oib_service_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.oibserviceevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('oib_service_event', 'oib_program'), name='unique_oib_service_event_oib_program')],
            },
        ),
    ]
