# Generated by Django 5.1.7 on 2025-08-21 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0118_remove_historicaloibserviceeventcontact_oib_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oibserviceeventoibprogram',
            name='oib_program',
        ),
        migrations.RemoveField(
            model_name='oibserviceeventoibprogram',
            name='oib_service_event',
        ),
        migrations.AddField(
            model_name='historicaloibserviceevent',
            name='organizing_department',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.oibprogram'),
        ),
        migrations.AddField(
            model_name='oibserviceevent',
            name='organizing_department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='lynx.oibprogram'),
        ),
        migrations.DeleteModel(
            name='HistoricalOIBServiceEventOIBProgram',
        ),
        migrations.DeleteModel(
            name='OIBServiceEventOIBProgram',
        ),
    ]
