# Generated by Django 5.1.7 on 2025-08-21 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0119_remove_oibserviceeventoibprogram_oib_program_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oibserviceevent',
            old_name='organizing_department',
            new_name='organizing_program',
        ),
        migrations.RemoveField(
            model_name='historicaloibserviceevent',
            name='organizing_department',
        ),
        migrations.AddField(
            model_name='historicaloibserviceevent',
            name='organizing_program',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.oibprogram'),
        ),
    ]
