# Generated by Django 5.1.7 on 2025-09-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0120_rename_organizing_department_oibserviceevent_organizing_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oiboutcomechoice',
            name='outcome_types',
            field=models.ManyToManyField(through='lynx.OIBOutcomeTypeChoice', to='lynx.oiboutcometype'),
        ),
    ]
