# Generated by Django 5.1.7 on 2025-09-08 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0121_rename_OibOutcome_to_OIBOutcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloiboutcome',
            name='grant_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloiboutcome',
            name='oib_service_delivery_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.oibservicedeliverytype'),
        ),
        migrations.AddField(
            model_name='historicaloiboutcome',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oiboutcome',
            name='grant_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oiboutcome',
            name='oib_service_delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lynx.oibservicedeliverytype'),
        ),
        migrations.AddField(
            model_name='oiboutcome',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
