# Generated by Django 5.1.7 on 2025-09-19 00:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0122_OIBOutcome_add_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=64, unique=True)),
                ('long_name', models.CharField(max_length=255)),
                ('is_oib', models.BooleanField(default=False)),
                ('min_age', models.SmallIntegerField(default=-1, help_text='-1 = no minimum age')),
                ('max_age', models.SmallIntegerField(default=-1, help_text='-1 = no maximum age')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProgram',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('program', models.CharField(db_index=True, max_length=64)),
                ('long_name', models.CharField(max_length=255)),
                ('is_oib', models.BooleanField(default=False)),
                ('min_age', models.SmallIntegerField(default=-1, help_text='-1 = no minimum age')),
                ('max_age', models.SmallIntegerField(default=-1, help_text='-1 = no maximum age')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical program',
                'verbose_name_plural': 'historical programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContactProgram',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('program_is_oib', models.BooleanField(default=False, editable=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('age_verified', models.BooleanField(default=True, help_text='False when no DOB available to validate against')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.contact')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.program')),
            ],
            options={
                'verbose_name': 'historical contact program',
                'verbose_name_plural': 'historical contact programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ContactProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_is_oib', models.BooleanField(default=False, editable=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('age_verified', models.BooleanField(default=True, help_text='False when no DOB available to validate against')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.contact')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lynx.program')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='lynx.ContactProgram', to='lynx.program'),
        ),
        migrations.AddIndex(
            model_name='contactprogram',
            index=models.Index(fields=['contact', 'program_is_oib', 'end_date'], name='lynx_contac_contact_3ee980_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactprogram',
            constraint=models.UniqueConstraint(fields=('contact', 'program'), name='unique_contact_program'),
        ),
        migrations.AddConstraint(
            model_name='contactprogram',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='cp_start_before_end'),
        ),
    ]
