# Generated by Django 5.1.7 on 2025-09-14 18:27

from django.db import migrations
from datetime import date

BOOL_TO_PROGRAM = {
    'sip_client': 'SIP',
    'sip1854_client': 'ILP',
    'core_client': 'CORE',
    'careers_plus': 'CareersPlus',
    # 'careers_plus_youth': 'CareersPlus Youth',  # REMOVED: see below
}

OIB_PROGRAMS = {'SIP', 'ILP'}

PROGRAM_LONG_NAMES = {
    'SIP': 'Senior Impact Program',
    'ILP': 'Independent Living Program',
    'CORE': 'Core Skills Program',
    'CareersPlus': 'CareersPlus',
}

PROGRAM_AGES = {
    'SIP': (55, -1),
    'ILP': (18, 54),
    'CORE': (-1, -1),
    'CareersPlus': (-1, 22),
}
DEFAULT_AGES = (-1, -1)

def ensure_programs(apps, schema_editor):
    Program = apps.get_model('lynx', 'Program')
    existing = {p.program: p for p in Program.objects.all()}
    to_create = []
    for program in set(BOOL_TO_PROGRAM.values()):
        if program not in existing:
            long_name = PROGRAM_LONG_NAMES.get(program, program)
            min_age, max_age = PROGRAM_AGES.get(program, DEFAULT_AGES)
            to_create.append(Program(
                program=program,
                long_name=long_name,
                is_oib=program in OIB_PROGRAMS,
                min_age=min_age,
                max_age=max_age,
            ))
    if to_create:
        Program.objects.bulk_create(to_create, ignore_conflicts=True)

# See NOTE 2025_09_18_1955
# def ensure_program_overlap(apps, schema_editor):
#     Program = apps.get_model('lynx', 'Program')
#     ProgramOverlap = apps.get_model('lynx', 'ProgramOverlap')
#     # Get program IDs
#     yib = Program.objects.filter(program='ILP').first()
#     cp = Program.objects.filter(program='CareersPlus').first()
#     if yib and cp:
#         a_id, b_id = sorted([yib.id, cp.id])
#         # Overlap allowed for ages 18-22
#         ProgramOverlap.objects.get_or_create(
#             program_a_id=a_id,
#             program_b_id=b_id,
#             defaults={'min_age': 18, 'max_age': 22}
#         )

def pick_start_date(contact, Intake):
    latest_intake = (
        Intake.objects
        .filter(contact_id=contact.id)
        .exclude(intake_date__isnull=True)
        .order_by('-intake_date')
        .first()
    )
    if latest_intake and latest_intake.intake_date:
        return latest_intake.intake_date
    if getattr(contact, 'created', None):
        return contact.created.date() if hasattr(contact.created, 'date') else contact.created
    return date.today()

def forwards(apps, schema_editor):
    Contact = apps.get_model('lynx', 'Contact')
    Program = apps.get_model('lynx', 'Program')
    ContactProgram = apps.get_model('lynx', 'ContactProgram')
    Intake = apps.get_model('lynx', 'Intake')

    ensure_programs(apps, schema_editor)
    # ensure_program_overlap(apps, schema_editor)
    prog_by_code = {p.program: p for p in Program.objects.all()}

    fields = ['id'] + list(BOOL_TO_PROGRAM.keys()) + ['careers_plus_youth']
    qs = Contact.objects.only(*fields)

    batch = []
    BATCH = 1000

    def flush():
        nonlocal batch
        if batch:
            ContactProgram.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []

    for c in qs.iterator(chunk_size=2000):
        start = pick_start_date(c, Intake)
        # Migrate all legacy booleans except careers_plus_youth
        for field, program in BOOL_TO_PROGRAM.items():
            if getattr(c, field, False):
                p = prog_by_code.get(program)
                if not p:
                    continue
                batch.append(ContactProgram(
                    contact_id=c.id,
                    program_id=p.id,
                    program_is_oib=p.is_oib,
                    start_date=start,
                    end_date=None,
                ))
                if len(batch) >= BATCH:
                    flush()
        # If careers_plus_youth is True, mark as careers_plus
        if getattr(c, 'careers_plus_youth', False):
            p = prog_by_code.get('CareersPlus')
            if p:
                batch.append(ContactProgram(
                    contact_id=c.id,
                    program_id=p.id,
                    program_is_oib=p.is_oib,
                    start_date=start,
                    end_date=None,
                ))
                if len(batch) >= BATCH:
                    flush()
    flush()

def backwards(apps, schema_editor):
    Contact = apps.get_model('lynx', 'Contact')
    Program = apps.get_model('lynx', 'Program')
    ContactProgram = apps.get_model('lynx', 'ContactProgram')

    code_to_field = {v: k for k, v in BOOL_TO_PROGRAM.items()}
    code_to_field['CareersPlus'] = 'careers_plus_youth'  # For backwards compatibility
    prog_by_id = {p.id: p.program for p in Program.objects.all()}

    for cp in ContactProgram.objects.filter(end_date__isnull=True).iterator():
        program = prog_by_id.get(cp.program_id)
        field = code_to_field.get(program)
        if field and hasattr(Contact, field):
            Contact.objects.filter(id=cp.contact_id).update(**{field: True})

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0123_add_program_m2m_contact'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]