# Generated by Django 5.1.7 on 2025-09-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0124_migrate_to_program_m2m_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontactinfoview',
            name='core_client',
        ),
        migrations.RemoveField(
            model_name='historicalcontactinfoview',
            name='sip1854_client',
        ),
        migrations.RemoveField(
            model_name='historicalcontactinfoview',
            name='sip_client',
        ),
        migrations.AddField(
            model_name='historicalcontactinfoview',
            name='programs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
