# Generated by Django 5.1.7 on 2025-09-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0125_remove_historicalcontactinfoview_core_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='access_news',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='careers_plus',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='careers_plus_youth',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='core_client',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='other_services',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sip1854_client',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sip_client',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='volunteer_check',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='access_news',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='careers_plus',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='careers_plus_youth',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='core_client',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='other_services',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='sip1854_client',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='sip_client',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='volunteer_check',
        ),
    ]
