# Generated by Django 5.1.7 on 2025-09-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0126_remove_contact_access_news_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactprogram',
            name='unique_contact_program',
        ),
    ]
