# Generated by Django 5.1.7 on 2025-09-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0127_remove_contactprogram_unique_contact_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalintake',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='age_group',
        ),
    ]
