# Generated by Django 5.1.7 on 2025-09-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0128_remove_intake_age_group'),
    ]

    operations = [
        # Drop existing view (if present) to remove dependency on the removed column
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS lynx_contactinfoview CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Recreate the ContactInfo view with a literal CASE expression that computes age_group
        migrations.RunSQL(
r"""
CREATE VIEW lynx_contactinfoview AS
SELECT c.id,
       concat(last_name, ', ', first_name) AS full_name,
       first_name,
       last_name,
       a.county,
       a.zip_code,
       REPLACE(REPLACE(REPLACE(REPLACE(p.phone, ' ', ''), '-', ''), ')', ''), '(', '') as phone,
       e.email,
       i.intake_date,
       CASE
         WHEN i.birth_date IS NULL THEN NULL
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) < 18 THEN 'younger than 18'
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) BETWEEN 18 AND 24 THEN '18-24'
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) BETWEEN 25 AND 34 THEN '25-34'
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) BETWEEN 35 AND 44 THEN '35-44'
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) BETWEEN 45 AND 54 THEN '45-54'
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) BETWEEN 55 AND 64 THEN '55-64'
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) BETWEEN 65 AND 74 THEN '65-74'
         WHEN date_part('year', age(COALESCE(i.intake_date, CURRENT_DATE), i.birth_date)) BETWEEN 75 AND 84 THEN '75-84'
         ELSE '85 and older'
       END AS age_group,
       a.address_one,
       a.address_two,
       a.suite,
       a.city,
       a.state,
       a.bad_address,
       c.do_not_contact,
       c.deceased,
       c.remove_mailing,
       a.region,
       phone AS full_phone,
       c.active,
       array_to_string(array_agg(pr.program), ',') AS programs
FROM lynx_contact AS c
LEFT JOIN LATERAL (
    SELECT ii.intake_date, ii.birth_date
    FROM lynx_intake ii
    WHERE ii.contact_id = c.id AND ii.birth_date IS NOT NULL
    ORDER BY ii.intake_date DESC NULLS LAST
    LIMIT 1
) i ON TRUE
LEFT JOIN lynx_address AS a ON a.contact_id = c.id
LEFT JOIN lynx_phone  AS p ON p.contact_id = c.id
LEFT JOIN lynx_email AS e ON e.contact_id = c.id
LEFT JOIN lynx_contactprogram cp ON cp.contact_id = c.id
LEFT JOIN lynx_program pr ON cp.program_id = pr.id
GROUP BY c.id, a.county, a.zip_code, p.phone, e.email, i.intake_date, i.birth_date,
            a.address_one, a.address_two, a.suite, a.city, a.state, a.bad_address,
            c.do_not_contact, c.deceased, c.remove_mailing, a.region, phone, c.active
""",
            reverse_sql="DROP VIEW IF EXISTS lynx_contactinfoview CASCADE;",
        ),
    ]