# Generated by Django 5.1.7 on 2025-09-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0129_recreate_contactinfoview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloibserviceevent',
            name='organizing_program',
        ),
        migrations.RemoveField(
            model_name='oibserviceevent',
            name='organizing_program',
        ),
        migrations.DeleteModel(
            name='HistoricalOIBProgram',
        ),
        migrations.DeleteModel(
            name='OIBProgram',
        ),
    ]
