# Generated by Django 5.1.7 on 2025-10-12 18:16

from itertools import chain
from django.db import migrations
from datetime import timedelta, date

# === WARNING ===========================================================
# This migration will fail when applying to a pre-service event db dump
# AFTER the old implementation models (i.e., SipNote, Sip1854Note, SipPlan,
# Sip1854Plan) have been removed.
# =======================================================================

def migrate_legacy_plans(apps, schema_editor):
    """
    Consolidate identical notes (SipNote.note or Sip1854Note.note) into a single
    OIBServiceEvent and associate all participating clients with that event.
    """
    User = apps.get_model('auth', 'User')

    # Previous implementation's models
    SipNote = apps.get_model('lynx', 'SipNote')
    Sip1854Note = apps.get_model('lynx', 'Sip1854Note')

    # Service event-based models
    OIBServiceEvent = apps.get_model('lynx', 'OIBServiceEvent')
    OIBService = apps.get_model('lynx', 'OIBService')
    OIBServiceDeliveryType = apps.get_model('lynx', 'OIBServiceDeliveryType')
    OIBServiceEventContact = apps.get_model('lynx', 'OIBServiceEventContact')
    OIBServiceEventInstructor = apps.get_model('lynx', 'OIBServiceEventInstructor')
    OIBServiceEventContactRole = apps.get_model('lynx', 'OIBServiceEventContactRole')
    OIBServiceEventInstructorRole = apps.get_model('lynx', 'OIBServiceEventInstructorRole')
    OIBServiceEventOIBService = apps.get_model('lynx', 'OIBServiceEventOIBService')
    OIBOutcome = apps.get_model('lynx', 'OIBOutcome')
    OIBOutcomeTypeChoice = apps.get_model('lynx', 'OIBOutcomeTypeChoice')

    # Creating lookup tables from small tables
    service_cache = {svc.id: svc for svc in OIBService.objects.all()}
    delivery_type_cache = {dt.id: dt for dt in OIBServiceDeliveryType.objects.all()}
    outcome_type_choice_cache = {otc.id: otc for otc in OIBOutcomeTypeChoice.objects.all()}
    contact_role_cache = {role.id: role for role in OIBServiceEventContactRole.objects.all()}
    instructor_role_cache = {role.id: role for role in OIBServiceEventInstructorRole.objects.all()}

    # Default roles
    ## default client: participating_client
    default_client_role = contact_role_cache.get(0) or next(iter(contact_role_cache.values()), None)
    ## default instructor: "instructor"
    default_instructor_role = instructor_role_cache.get(0) or next(iter(instructor_role_cache.values()), None)

    # --- Helpers -------------------------------------------------------------

    def map_plan_name_to_delivery_type(plan_name):
        """
        Map plan name to OIBServiceDeliveryType by string matching.
        Default to 'support group' (id 2) when no match.
        """
        default = delivery_type_cache.get(2, delivery_type_cache.get(0))
        if not plan_name:
            return default

        name = plan_name.lower()
        if "in-home" in name or "in home" in name or "inhome" in name:
            return delivery_type_cache.get(1, default)
        if "support group" in name:
            return delivery_type_cache.get(2, default)
        if "training seminar" in name or "workshop" in name:
            return delivery_type_cache.get(3, default)
        if "community integration" in name:
            return delivery_type_cache.get(4, default)
        if "retreat" in name:
            return delivery_type_cache.get(5, default)
        return default

    def convert_class_hours_to_duration(class_hours):
        """Convert class hours (float-like) to timedelta; default 1 hour."""
        if class_hours is None:
            return timedelta(hours=1)
        try:
            return timedelta(hours=float(class_hours))
        except (ValueError, TypeError):
            return timedelta(hours=1)

    def extract_outcomes_from_plan(plan):
        """Return list of OIBOutcomeTypeChoice from BasePlan outcome fields."""
        outcomes = []

        v = getattr(plan, 'living_plan_progress', None)
        if v == "Plan not complete":
            outcomes.append(outcome_type_choice_cache.get(9))
        elif v == "Plan complete, feeling more confident in ability to maintain living situation":
            outcomes.append(outcome_type_choice_cache.get(10))
        elif v == "Plan complete, no difference in ability to maintain living situation":
            outcomes.append(outcome_type_choice_cache.get(11))
        elif v == "Plan complete, feeling less confident in ability to maintain living situation":
            outcomes.append(outcome_type_choice_cache.get(12))

        v = getattr(plan, 'community_plan_progress', None)
        if v == "Plan not complete":
            outcomes.append(outcome_type_choice_cache.get(13))
        elif v == "Plan complete, feeling more confident in ability to maintain living situation":
            outcomes.append(outcome_type_choice_cache.get(14))
        elif v == "Plan complete, no difference in ability to maintain living situation":
            outcomes.append(outcome_type_choice_cache.get(15))
        elif v == "Plan complete, feeling less confident in ability to maintain living situation":
            outcomes.append(outcome_type_choice_cache.get(16))

        v = getattr(plan, 'employment_outcomes', None)
        if v == "Not Interested in Employment":
            outcomes.append(outcome_type_choice_cache.get(17))
        elif v == "Less Likely to Seek Employment":
            outcomes.append(outcome_type_choice_cache.get(18))
        elif v == "Unsure about Seeking Employment":
            outcomes.append(outcome_type_choice_cache.get(19))
        elif v == "More Likely to Seek Employment":
            outcomes.append(outcome_type_choice_cache.get(20))

        v = getattr(plan, 'at_outcomes', None)
        if v == "Not assessed":
            outcomes.append(outcome_type_choice_cache.get(1))
        elif v == "Assessed with improved independence":
            outcomes.append(outcome_type_choice_cache.get(2))
        elif v == "Assessed and maintained independence":
            outcomes.append(outcome_type_choice_cache.get(3))
        elif v == "Assessed with decreased independence":
            outcomes.append(outcome_type_choice_cache.get(4))

        v = getattr(plan, 'ila_outcomes', None)
        if v == "Not assessed":
            outcomes.append(outcome_type_choice_cache.get(5))
        elif v == "Assessed with improved independence":
            outcomes.append(outcome_type_choice_cache.get(6))
        elif v == "Assessed and maintained independence":
            outcomes.append(outcome_type_choice_cache.get(7))
        elif v == "Assessed with decreased independence":
            outcomes.append(outcome_type_choice_cache.get(8))

        return [o for o in outcomes if o is not None]

    def create_outcomes(service_event, note_with_plan_user_contact, alt_user):
        """
        Create OIBOutcome records for the given note's plan.
        Uses note.fiscal_year for grant_year (leading 4-digit part), falling back silently.
        """
        note = note_with_plan_user_contact
        plan = getattr(note, 'sip_plan', None)
        if not plan or not getattr(plan, 'contact_id', None):
            return

        outcomes = extract_outcomes_from_plan(plan)
        if not outcomes:
            return

        # Grant year: take first 4 digits from fiscal_year if present
        grant_year = None
        fy = getattr(note, 'fiscal_year', None) or ''
        if isinstance(fy, str) and len(fy) >= 4 and fy[:4].isdigit():
            grant_year = fy[:4]

        for outcome_type_choice in outcomes:
            try:
                OIBOutcome.objects.create(
                    oib_outcome_type_choice=outcome_type_choice,
                    contact_id=plan.contact_id,
                    user_id=getattr(plan, 'user_id', None) or getattr(alt_user, 'id', None),
                    oib_service_delivery_type=service_event.oib_service_delivery_type,
                    grant_year=grant_year
                )
            except Exception:
                continue

    def extract_services_from_note_and_plan(note_with_plan_user_contact):
        """
        Map OIBService ids to BasePlan and BasePlanNote service-related fields.
        (Both prev implementation model's have service-related boolean fields,
         some were even redundant within the same model, hence the mess.)
        """
        note = note_with_plan_user_contact
        plan = getattr(note, 'sip_plan', None)
        services = set()

        # Note-level service-related flags
        if getattr(note, 'at_devices', False) or getattr(note, 'at_services', False):
            services.add(0)  # AT
        if getattr(note, 'orientation', False):
            services.add(1)  # O&M
        if getattr(note, 'communications', False):
            services.add(2)  # Comm
        if getattr(note, 'independent_living', False) or getattr(note, 'dls', False):
            services.add(3)  # DLS
        if getattr(note, 'advocacy', False):
            services.add(4)  # Advocacy
        if getattr(note, 'counseling', False):
            services.add(5)  # AC
        if getattr(note, 'support', False):
            services.add(6)  # SS
        if getattr(note, 'information', False):
            services.add(7)  # IR
        if getattr(note, 'services', False):
            services.add(8)  # other IL/A

        # Plan-level service-related flags
        if plan:
            if getattr(plan, 'at_services', False):
                services.add(0)
            if getattr(plan, 'orientation', False):
                services.add(1)
            if getattr(plan, 'communications', False):
                services.add(2)
            if getattr(plan, 'independent_living', False) or getattr(plan, 'dls', False):
                services.add(3)
            if getattr(plan, 'advocacy', False):
                services.add(4)
            if getattr(plan, 'counseling', False):
                services.add(5)
            if getattr(plan, 'support_services', False):
                services.add(6)
            if getattr(plan, 'information', False):
                services.add(7)
            if getattr(plan, 'other_services', False):
                services.add(8)

        return services

    def add_extracted_services(service_event, note_with_plan_user_contact):
        """
        Add OIBServiceEventOIBService rows for the given note's derived services.
        Safe for repeated calls (checks existence).
        """
        services = extract_services_from_note_and_plan(note_with_plan_user_contact)
        for service_id in services:
            service = service_cache.get(service_id)
            if not service:
                continue
            exists = OIBServiceEventOIBService.objects.filter(
                oib_service_event=service_event,
                oib_service_id=service_id
            ).exists()
            if not exists:
                OIBServiceEventOIBService.objects.create(
                    oib_service_event=service_event,
                    oib_service=service
                )

    # --- Consolidate notes by identical text --------------------------------

    # Groups keyed by exact note text AND note_date (after strip)
    # Each payload keeps representative fields + all notes/contacts
    groups = {}

    for note in chain(
        SipNote.objects.select_related('contact', 'user', 'sip_plan').iterator(),
        Sip1854Note.objects.select_related('contact', 'user', 'sip_plan').iterator(),
    ):
        try:
            if not getattr(note, 'contact_id', None):
                continue

            note_text = (note.note or "").strip()
            # normalize the note date used for grouping
            note_date = note.note_date or (note.created.date() if getattr(note, 'created', None) else date.today())

            # use (note_text, note_date) as the group key so both must match
            key = (note_text, note_date)

            if key not in groups:
                # Determine delivery type from related plan, else default to "support group" (id 2)
                delivery_type = delivery_type_cache.get(2)
                if getattr(note, 'sip_plan', None) and getattr(note.sip_plan, 'plan_name', None):
                    delivery_type = map_plan_name_to_delivery_type(note.sip_plan.plan_name) or delivery_type

                groups[key] = {
                    'representative': note,                     # first note encountered
                    'delivery_type_id': getattr(delivery_type, 'id', None),
                    'date': note_date,
                    'class_hours': note.class_hours,
                    'entered_by_id': getattr(note, 'user_id', None),
                    'instructor_name': (note.instructor or "").strip(),
                    'contact_ids': set(),
                    'notes': [],                                # all notes in this group
                }

            g = groups[key]
            g['contact_ids'].add(note.contact_id)
            g['notes'].append(note)

            # Prefer first non-null class_hours
            if g['class_hours'] is None and note.class_hours is not None:
                g['class_hours'] = note.class_hours

            # Prefer first entered_by
            if not g['entered_by_id'] and getattr(note, 'user_id', None):
                g['entered_by_id'] = note.user_id

            # Prefer first non-empty instructor name
            if not g['instructor_name'] and (note.instructor or "").strip():
                g['instructor_name'] = (note.instructor or "").strip()

        except Exception:
            continue

    # Create one service event per group and attach all participants and services
    for (note_text, note_date), g in groups.items():
        try:
            delivery_type = delivery_type_cache.get(g['delivery_type_id']) if g['delivery_type_id'] is not None else delivery_type_cache.get(2)
            entered_by = User.objects.filter(pk=g['entered_by_id']).first() if g['entered_by_id'] else None
            if not entered_by:
                entered_by = User.objects.filter(is_staff=True).first()

            service_event = OIBServiceEvent.objects.create(
                oib_service_delivery_type=delivery_type,
                date=note_date,  # use the normalized note_date from the group key
                length=convert_class_hours_to_duration(g['class_hours']),
                note=note_text,  # consolidated note text
                entered_by=entered_by
            )

            # Attach all unique contacts
            for contact_id in g['contact_ids']:
                if not OIBServiceEventContact.objects.filter(oib_service_event=service_event, contact_id=contact_id).exists():
                    OIBServiceEventContact.objects.create(
                        oib_service_event=service_event,
                        contact_id=contact_id,
                        oib_service_event_contact_role=default_client_role
                    )

            # Attach services derived from each grouped note (dedup-safe via existence check)
            for n in g['notes']:
                add_extracted_services(service_event, n)

            # Instructor: prefer note.user, else resolve by instructor name
            instructor = None
            rep = g['representative']
            if getattr(rep, 'user_id', None):
                instructor = User.objects.filter(pk=rep.user_id).first()
            if not instructor and g['instructor_name']:
                parts = g['instructor_name'].split()
                if len(parts) > 1:
                    maybe = User.objects.filter(first_name__iexact=parts[0], last_name__iexact=parts[-1]).first()
                    instructor = maybe or instructor
            if instructor and not OIBServiceEventInstructor.objects.filter(oib_service_event=service_event, instructor_id=instructor.pk).exists():
                OIBServiceEventInstructor.objects.create(
                    oib_service_event=service_event,
                    instructor=instructor,
                    oib_service_event_instructor_role=default_instructor_role
                )

            # Outcomes: create per note's plan to preserve per-client outcomes
            for n in g['notes']:
                try:
                    create_outcomes(service_event, n, entered_by)
                except Exception:
                    continue

        except Exception:
            continue


def reverse_migration(apps, schema_editor):
    # Not reversible
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0130_drop_oibprogram'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_plans, reverse_migration),
    ]