# Generated by Django 5.1.7 on 2025-10-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0131_migrate_plan_to_service_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalVolunteer',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
