# Generated by Django 5.1.7 on 2025-10-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0132_drop_volunteer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactprogram',
            name='lynx_contac_contact_3ee980_idx',
        ),
        migrations.RemoveField(
            model_name='contactprogram',
            name='program_is_oib',
        ),
        migrations.RemoveField(
            model_name='historicalcontactprogram',
            name='program_is_oib',
        ),
        migrations.AddIndex(
            model_name='contactprogram',
            index=models.Index(fields=['contact', 'start_date', 'end_date'], name='lynx_contac_contact_8fbf24_idx'),
        ),
    ]
