# Generated by Django 5.1.7 on 2025-10-26 13:08

from django.db import migrations, models, transaction

def set_defaults(apps, _schema_editor):
    O = apps.get_model('lynx', 'OIBOutcomeTypeChoice')
    # These IDs correspond to the following outcome types and choices:
    # "AT Goal Outcome"                        "Assessed with improved independence"
    # "IL/A Service Goal Outcome"              "Assessed with improved independence"
    # "Living Situation Outcome"               "Plan complete, ..."
    # "Home and Community Involvement Outcome" "Plan complete, ..."
    # "Employment Outcome"                     "Not Interested in Employment"
    target_ids = [2, 6, 10, 14, 17]
    with transaction.atomic():
        for pk in target_ids:
            # No error checks because the IDs above have to exist (added in prior migrations),
            # so if they don't, we want the migration to fail.
            row = O.objects.get(pk=pk)
            otc_id = row.oib_outcome_type_id
            # clear any other default for this outcome type (exclude target row)
            O.objects.filter(oib_outcome_type_id=otc_id).exclude(pk=pk).update(default_choice=False)
            row.default_choice = True
            row.save(update_fields=['default_choice'])

def unset_defaults(apps, _schema_editor):
    O = apps.get_model('lynx', 'OIBOutcomeTypeChoice')
    O.objects.filter(pk__in=[1, 5, 9, 13, 17]).update(default_choice=False)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0133_remove_contactprogram_program_is_oib'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloiboutcometypechoice',
            name='default_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oiboutcometypechoice',
            name='default_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='oiboutcometypechoice',
            constraint=models.UniqueConstraint(
                condition=models.Q(('default_choice', True)),
                fields=('oib_outcome_type',),
                name='one_default_per_outcome_type'
            ),
        ),
        migrations.RunPython(set_defaults, unset_defaults),
    ]
