# Generated by Django 5.1.7 on 2025-12-02 23:36

import django.db.models.deletion
from django.db import migrations, models

STATUSES = (("Assigned", "Assigned"), ("In Progress", "In Progress"), ("Completed", "Completed"))
ASSIGNMENT_PRIORITY = (("New", "New"), ("Returning", "Returning"))

def add_statuses_and_priorities(apps, schema_editor):
    AssignmentStatus = apps.get_model('lynx', 'AssignmentStatus')
    AssignmentPriority = apps.get_model('lynx', 'AssignmentPriority')
    for name, _ in STATUSES:
        AssignmentStatus.objects.get_or_create(name=name)
    for name, _ in ASSIGNMENT_PRIORITY:
        AssignmentPriority.objects.get_or_create(name=name)

def remove_statuses_and_priorities(apps, schema_editor):
    AssignmentStatus = apps.get_model('lynx', 'AssignmentStatus')
    AssignmentPriority = apps.get_model('lynx', 'AssignmentPriority')
    AssignmentStatus.objects.filter(name__in=[name for name, _ in STATUSES]).delete()
    AssignmentPriority.objects.filter(name__in=[name for name, _ in ASSIGNMENT_PRIORITY]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0134_oiboutcometypechoice_add_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='program_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='lynx.program'),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='program_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.program'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='lynx.assignmentpriority'),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='priority_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.assignmentpriority'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='lynx.assignmentstatus'),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='assignment_status_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.assignmentstatus'),
        ),
        migrations.RunPython(add_statuses_and_priorities, remove_statuses_and_priorities),
    ]
