# Generated by Django 5.1.7 on 2025-12-03 00:13

from django.db import migrations

def forwards(apps, schema_editor):
    Assignment = apps.get_model('lynx', 'Assignment')
    Program = apps.get_model('lynx', 'Program')
    AssignmentStatus = apps.get_model('lynx', 'AssignmentStatus')
    AssignmentPriority = apps.get_model('lynx', 'AssignmentPriority')

    # # create status rows
    # for name in ['Assigned', 'In Progress', 'Completed']:
    #     AssignmentStatus.objects.get_or_create(name=name)

    # # create priority rows
    # for name in ['New', 'Returning']:
    #     AssignmentPriority.objects.get_or_create(name=name)

    ilp_program = Program.objects.get(program='ILP')

    # null defaults
    sip_program = Program.objects.get(program='SIP')
    assigned_status = AssignmentStatus.objects.get(name='Assigned')
    new_priority = AssignmentPriority.objects.get(name='New')

    # Map existing assignments
    for a in Assignment.objects.all():
        # map program string -> Program row
        if a.program == 'SIP':
            a.program_fk = sip_program
        elif a.program == '1854':
            a.program_fk = ilp_program
        else:
            a.program_fk = sip_program

        # map assignment_status string -> AssignmentStatus
        if not a.assignment_status:
            a.assignment_status_fk = assigned_status
        else:
            try:
                st = AssignmentStatus.objects.get(name=a.assignment_status)
                a.assignment_status_fk = st
            except AssignmentStatus.DoesNotExist:
                pass

        # map priority string -> AssignmentPriority
        if not a.priority:
            a.priority_fk = new_priority
        else:
            try:
                pr = AssignmentPriority.objects.get(name=a.priority)
                a.priority_fk = pr
            except AssignmentPriority.DoesNotExist:
                pass

        # save using update to avoid calling any model.full_clean hooks
        Assignment.objects.filter(pk=a.pk).update(
            program_fk_id=(a.program_fk.id if a.program_fk else None),
            assignment_status_fk_id=(a.assignment_status_fk.id if a.assignment_status_fk else None),
            priority_fk_id=(a.priority_fk.id if a.priority_fk else None),
        )

def reverse(apps, schema_editor):
    # no-op reverse (you can optionally map back)
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('lynx', '0135_add_assignment_priority_status'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]