# Generated by Django 5.1.7 on 2025-12-03 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0136_replace_assignment_program_priority_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_status_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='lynx.assignmentstatus'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='priority_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='lynx.assignmentpriority'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='program_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='lynx.program'),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='assignment_status_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.assignmentstatus'),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='priority_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.assignmentpriority'),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='program_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.program'),
        ),
    ]
