# Generated by Django 5.1.7 on 2025-12-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0137_alter_assignment_assignment_status_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_status',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='assignment_status',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='program',
        ),
    ]
