# Generated by Django 5.1.7 on 2025-12-03 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0138_remove_assignment_assignment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_status_fk',
            new_name='assignment_status',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='priority_fk',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='program_fk',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='historicalassignment',
            old_name='assignment_status_fk',
            new_name='assignment_status',
        ),
        migrations.RenameField(
            model_name='historicalassignment',
            old_name='priority_fk',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='historicalassignment',
            old_name='program_fk',
            new_name='program',
        ),
    ]
