# Generated by Django 5.1.7 on 2025-12-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0139_rename_assignment_status_fk_assignment_assignment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontactinfoview',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='ContactInfoView',
        ),
        migrations.DeleteModel(
            name='HistoricalContactInfoView',
        ),
    ]
