# Generated by Django 5.1.7 on 2026-09-12 23:17

from django.db import migrations

def get_grant_year(service_event):
    if service_event.date.month >= 10:
        return service_event.date.year
    else:
        return service_event.date.year - 1

def construct_plan_name(service_event):
    grant_year = get_grant_year(service_event)
    plan_month_day = "10/01"
    service_delivery_type_name = getattr(service_event.oib_service_delivery_type, 'oib_service_delivery_type', '') or ""
    return f"{plan_month_day}/{grant_year} - {service_delivery_type_name or ''}"

def forwards_populate_plans(apps, schema_editor):
    OIBServiceEvent = apps.get_model('lynx', 'OIBServiceEvent')
    OIBPlan = apps.get_model('lynx', 'OIBPlan')

    qs = OIBServiceEvent.objects.all()
    for service_event in qs:
        plan_name = construct_plan_name(service_event)
        plan, _created = OIBPlan.objects.get_or_create(oib_plan_name=plan_name)

        OIBServiceEvent.objects.filter(pk=service_event.pk).update(oib_plan_id=plan.id)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0141_add_oibplan'),
    ]

    operations = [
        # populate newly created OIBPlan rows and assign events to them
        migrations.RunPython(forwards_populate_plans, reverse_code=migrations.RunPython.noop),
    ]
