# Generated by Django 5.1.7 on 2026-09-12 23:17

from django.db import migrations
from lynx import models as lm

def forwards_populate_plans(apps, schema_editor):
    qs = lm.OIBServiceEvent.objects.all()
    for service_event in qs:
        plan_name = service_event.construct_plan_name()
        plan, _created = lm.OIBPlan.objects.get_or_create(oib_plan_name=plan_name)

        lm.OIBServiceEvent.objects.filter(pk=service_event.pk).update(oib_plan_id=plan.id)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0141_add_oibplan'),
    ]

    operations = [
        # populate newly created OIBPlan rows and assign events to them
        migrations.RunPython(forwards_populate_plans, reverse_code=migrations.RunPython.noop),
    ]
