# Generated by Django 5.1.7 on 2026-09-13 22:53

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0142_fill_oibplan_with_oibserviceevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloibserviceeventcontact',
            name='oib_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.oibplan'),
        ),
        migrations.AddField(
            model_name='oibserviceeventcontact',
            name='oib_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lynx.oibplan'),
        ),
    ]
