# Generated by Django 5.1.7 on 2026-09-14 00:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0143_add_plans_to_oibserviceeventcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBirthDateCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_saved_birth_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalContactBirthDateCache',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_saved_birth_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical contact birth date cache',
                'verbose_name_plural': 'historical contact birth date caches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicaloibserviceevent',
            name='oib_plan',
        ),
        migrations.RemoveField(
            model_name='oibserviceevent',
            name='oib_plan',
        ),
        migrations.AddField(
            model_name='contactbirthdatecache',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.contact'),
        ),
        migrations.AddField(
            model_name='historicalcontactbirthdatecache',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lynx.contact'),
        ),
        migrations.AddField(
            model_name='historicalcontactbirthdatecache',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contactbirthdatecache',
            constraint=models.UniqueConstraint(fields=('contact',), name='unique_contact_birth_date'),
        ),
    ]
