# Generated by Django 5.1.7 on 2026-09-14 00:50

from django.db import migrations, models
from django.apps import apps
from datetime import date

def get_grant_year(service_event):
    if service_event.date.month >= 10:
        return service_event.date.year
    else:
        return service_event.date.year - 1

def construct_plan_name(service_event):
    grant_year = get_grant_year(service_event)
    plan_month_day = "10/01"
    service_delivery_type_name = getattr(service_event.oib_service_delivery_type, 'oib_service_delivery_type', '') or ""
    return f"{plan_month_day}/{grant_year} - {service_delivery_type_name or ''}"

def maybe_age_on(contact, on_date):
    intake = (
        contact.intake_set
        .exclude(birth_date__isnull=True)
        .order_by('-intake_date')
        .first()
    )
    dob = intake.birth_date if intake else None
    if not dob:
        return None
    on_date = on_date or date.today()
    return on_date.year - dob.year - ((on_date.month, on_date.day) < (dob.month, dob.day))

def get_age_appropriate_oib_program(contact_age):
    """
    Return the appropriate OIB Program for a contact of a given age - no matter if
    contact is an OIB client or not.
    """
    Program = apps.get_model('lynx', 'Program')
    if contact_age is None:
        return None

    oib_programs = Program.objects.filter(is_oib=True)
    qs = oib_programs.filter(
        models.Q(min_age__lte=contact_age) | models.Q(min_age=-1),
        models.Q(max_age__gte=contact_age) | models.Q(max_age=-1),
    )
    # OIB programs should be mutually exclusive by age, so there should be at most
    # one match - but wwho knows what gets misconfigured in the admin page or what
    # the DOR future brings.
    program = qs.first()
    return program

def get_program(service_event, contact):
    client_age_at_event = maybe_age_on(contact, service_event.date)
    return get_age_appropriate_oib_program(client_age_at_event)

def forwards_populate_plans(apps, schema_editor):
    OIBServiceEventContact = apps.get_model('lynx', 'OIBServiceEventContact')
    OIBPlan = apps.get_model('lynx', 'OIBPlan')
    ContactBirthDateCache = apps.get_model('lynx', 'ContactBirthDateCache')
    Intake = apps.get_model('lynx', 'Intake')

    qs = OIBServiceEventContact.objects.all()
    for service_event_contact in qs:
        client = service_event_contact.contact
        service_event = service_event_contact.oib_service_event
        plan_name = construct_plan_name(service_event)
        program = get_program(service_event, client)
        program_name = getattr(program, 'program', program) if program is not None else None

        plan, _created = OIBPlan.objects.get_or_create(oib_plan_name=plan_name, program_name=program_name)
        OIBServiceEventContact.objects.filter(pk=service_event_contact.pk).update(oib_plan_id=plan.id)

        intake = Intake.objects.filter(contact=client).order_by('-intake_date').first()
        # Lot of clients have no intake (yet?)
        if intake is not None:
            if intake.birth_date is None:
                intake.birth_date = "1900-01-01"
                intake.save()
            ContactBirthDateCache.objects.get_or_create(contact=client, last_saved_birth_date=intake.birth_date)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0144_contactbirthdatecache_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_populate_plans, reverse_code=migrations.RunPython.noop),
    ]
