# Generated by Django 5.1.7 on 2026-09-14 00:50

from django.db import migrations
from django.apps import apps

def get_grant_year(service_event):
    if service_event.date.month >= 10:
        return service_event.date.year
    else:
        return service_event.date.year - 1

def construct_plan_name(service_event):
    grant_year = get_grant_year(service_event)
    plan_month_day = "10/01"
    service_delivery_type_name = getattr(service_event.oib_service_delivery_type, 'oib_service_delivery_type', '') or ""
    return f"{plan_month_day}/{grant_year} - {service_delivery_type_name or ''}"

def forwards_populate_plans(apps, schema_editor):
    OIBServiceEventContact = apps.get_model('lynx', 'OIBServiceEventContact')
    OIBPlan = apps.get_model('lynx', 'OIBPlan')
    ContactBirthDateCache = apps.get_model('lynx', 'ContactBirthDateCache')
    Intake = apps.get_model('lynx', 'Intake')

    qs = OIBServiceEventContact.objects.all()
    for service_event_contact in qs:
        client = service_event_contact.contact
        service_event = service_event_contact.oib_service_event
        plan_name = construct_plan_name(service_event)

        plan, _created = OIBPlan.objects.get_or_create(oib_plan_name=plan_name)
        OIBServiceEventContact.objects.filter(pk=service_event_contact.pk).update(oib_plan_id=plan.id)

        intake = Intake.objects.filter(contact=client).order_by('-intake_date').first()
        # Lot of clients have no intake (yet?)
        if intake is not None:
            if intake.birth_date is None:
                intake.birth_date = "1900-01-01"
                intake.save()
            ContactBirthDateCache.objects.get_or_create(contact=client, last_saved_birth_date=intake.birth_date)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0144_add_contactbirthdatecache'),
    ]

    operations = [
        migrations.RunPython(forwards_populate_plans, reverse_code=migrations.RunPython.noop),
    ]
