# Generated by Django 5.1.7 on 2026-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0145_fill_oibplan_then_ref_in_oibsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloibserviceeventcontact',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oibserviceeventcontact',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
