# Generated by Django 5.1.7 on 2026-09-20 23:43

from django.db import migrations, models
from django.apps import apps
from datetime import datetime

def _get_grant_year(service_event):
    if service_event.date.month >= 10:
        return service_event.date.year
    else:
        return service_event.date.year - 1

def construct_plan_name(service_event):
    grant_year = _get_grant_year(service_event)
    plan_month_day = "10/01"
    service_delivery_type_name = getattr(service_event.oib_service_delivery_type, 'oib_service_delivery_type', '') or ""
    return f"{plan_month_day}/{grant_year} - {service_delivery_type_name or ''}"

def _maybe_age_on(contact, on_date):
    dob = contact.intake_set.first().birth_date if contact.intake_set.exists() else datetime.strptime('1900-01-01', '%Y-%m-%d').date()
    return on_date.year - dob.year - ((on_date.month, on_date.day) < (dob.month, dob.day))

def _get_age_appropriate_oib_program(programs, contact_age):
    qs = programs.filter(
        models.Q(min_age__lte=contact_age) | models.Q(min_age=-1),
        models.Q(max_age__gte=contact_age) | models.Q(max_age=-1),
    )
    # OIB programs should be mutually exclusive by age, so there should be at most
    # one match - but wwho knows what gets misconfigured in the admin page or what
    # the DOR future brings.
    program = qs.first()
    return program

def get_program(programs, service_event, contact):
    client_age_at_event = _maybe_age_on(contact, service_event.date)
    return _get_age_appropriate_oib_program(programs, client_age_at_event)

def forwards_populate_plans(apps, schema_editor):
    OIBServiceEventContact = apps.get_model('lynx', 'OIBServiceEventContact')
    Program = apps.get_model('lynx', 'Program')
    oib_programs = Program.objects.filter(is_oib=True)

    qs = OIBServiceEventContact.objects.all()
    for service_event_contact in qs:
        client = service_event_contact.contact
        service_event = service_event_contact.oib_service_event
        program = get_program(oib_programs, service_event, client)
        program_name = getattr(program, 'program', program) if program is not None else None

        OIBServiceEventContact.objects.filter(pk=service_event_contact.pk).update(program_name=program_name)

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0146_add_program_name_to_oibsec'),
    ]

    operations = [
        migrations.RunPython(forwards_populate_plans, reverse_code=migrations.RunPython.noop),
    ]
